### ISSUE TITLE
Fix save/load fn Prophet detector Python 3.6

### ISSUE THREAD

**Issue by arnaudvl** [SeldonIO/alibi-detect#106]
Can put a temporary fix in place by wiping the stan backend logger as an attribute: https://github.com/facebook/prophet/issues/1361

**Comment by dan-r95** [comment]
I fixed that on my fork
https://github.com/dan-r95/alibi-detect/commit/02e46131187fe87779ec369232d9162728c46ff2

**Comment by jklaise** [comment]
Deprioritized as Python 3.6 will be EOL by December 2021.

**Comment by ascillitoe** [comment]
@arnaudvl @jklaise can we close this since we no longer support 3.6?

**Comment by arnaudvl** [comment]
Yes
