### ISSUE TITLE
Not able to import OutlierProphet

### ISSUE THREAD

**Issue by hassanmehmud** [SeldonIO/alibi-detect#115]
I tried to pip alibi-detect , results in successful install. But i am not able to import outlierProphet files.
Second issue not being able to import KSD drift although all requirements are satisfied.
I am getting following exception:
```File "/lib/python3.5/site-packages/creme/compat/__init__.py", line 1, in <module>
    from .creme_to_sklearn import convert_creme_to_sklearn

  File "t/lib/python3.5/site-packages/creme/compat/creme_to_sklearn.py", line 221
    raise ValueError(f'n_classes is more than 2 but {self.creme_estimator} is a ' +
                                                                                ^
SyntaxError: invalid syntax
```

---------------------------------------------------------------------------

```from alibi_detect.cd import KSDrift


ImportError                               Traceback (most recent call last)
<ipython-input-38-254c7647900a> in <module>
----> 1 from alibi_detect.cd import KSDrift

ImportError: cannot import name 'KSDrift'
```

Thanks

**Comment by jklaise** [comment]
Hi!

Could you try upgrading to Python 3.6 or 3.7 as we don't support 3.5? I think the issue is the use of f-strings which isn't supported in Python 3.5

Also, the `KSDrift` component is not yet released on pip, so if you want to use it, you will have to install form source:
` pip install git+https://github.com/SeldonIO/alibi-detect.git`

**Comment by jklaise** [comment]
@hassanmehmud v0.4.0 is now released whihc includes the `KSDrift` and `MMDrift` components.

**Comment by gregorjohnen** [comment]
Hey @jklaise, I was having the same problem as @hassanmehmud but am using py version 3.8.5 Explicitely the installation stops when 'Collecting pystan<3.0'. Is there any solution to the problem?
