### ISSUE TITLE
Spectral Residual (Online) - doubt

### ISSUE THREAD

**Issue by MarceloNunesAlves** [SeldonIO/alibi-detect#122]
Hi!

In the Spectral Residual documentation there isn't anything about training data online, how does it work? I need a solution for identifying anomalies in real time but I don't understand how it works using the Spectral Residual. Is there documentation or example how I train the model incrementally?

Your project is fantastic and I'd like to contribute.

Thank you so much!

**Comment by arnaudvl** [comment]
Hi, thanks for the kind words! The Spectral Residual detector is not trained online and does not keep state. You just need to pass a univariate time series that fits in memory and the outliers will be computed on the fly. [This example](https://docs.seldon.io/projects/alibi-detect/en/latest/examples/od_sr_synth.html) should help you out. If you have multivariate time series or have enough (normal) training data you can use the [Seq2Seq](https://docs.seldon.io/projects/alibi-detect/en/latest/methods/seq2seq.html) detector, although it is not guaranteed that it is fast enough at inference time given the autoregressive behaviour. If you want online detection with incremental online training but not necessarily for time series, the [Mahalanobis Distance](https://docs.seldon.io/projects/alibi-detect/en/latest/methods/mahalanobis.html) could be a good fit.
