### ISSUE TITLE
How to define a random state?

### ISSUE THREAD

**Issue by gireeshkbogu** [SeldonIO/alibi-detect#123]
Hi, I get different results every time I run the Spectral Residue method. Is there a way to define the random state here? thanks.

**Comment by arnaudvl** [comment]
Hi @gireeshkbogu. There should be no randomness in the method itself, so can I assume it is in the data generation process?

**Comment by gireeshkbogu** [comment]
I believe `inject_outlier_ts` is the reason why I am getting random values. In the tutorial, you are injecting noise in the time-series data. Should I do this if I use my own data? Here is the code that I am using. Your thoughts will be much appreciated!

```
samples = df['temp'].values
X = samples.reshape(-1, 1).astype(np.float32)
data = inject_outlier_ts(X, perc_outlier=10, perc_window=10, n_std=2., min_std=1.)
```

**Comment by arnaudvl** [comment]
`inject_outlier_ts` indeed randomly injects outliers in the synthetic data just for the purpose of testing the outlier detection method. You shouldn't inject noise in your own time series, detecting the outliers without added noise will already be hard enough. :)
So in your case, you should detect outliers on `X` without the additional noise injection step.

**Comment by gireeshkbogu** [comment]
Thank you for the quick response. Can I run like this? I got an error at the

time_samples_1 = data_2['index'].values
time_samples = time_samples_1.reshape(-1, 1).astype(np.float32)

samples = data_2['temp'].values
X = samples.reshape(-1, 1).astype(np.float32)
data = X

data_threshold = data[:50, :]
od.infer_threshold(data_threshold, time_samples[:50], threshold_perc=90)
print('New threshold: {:.4f}'.format(od.threshold))


filepath = './'
save_detector(od, filepath)
od = load_detector(filepath)
od_preds = od.predict(data, time_samples, return_instance_score=True)
od_preds

plot_feature_outlier_ts(od_preds,
                        X_outlier,
                        od.threshold,
                        window=(1000, 1050),
                        t=time_samples,
                        X_orig=data)
 

Error
```
New threshold: 1.0583
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-5afa80175fcf> in <module>()
     23                         window=(1000, 1050),
     24                         t=time_samples,
---> 25                         X_orig=data)

6 frames
/usr/local/lib/python3.6/dist-packages/matplotlib/patches.py in set_linewidth(self, w)
    393                 w = mpl.rcParams['axes.linewidth']
    394 
--> 395         self._linewidth = float(w)
    396         # scale the dash pattern by the linewidth
    397         offset, ls = self._us_dashes

TypeError: only size-1 arrays can be converted to Python scalars
```

**Comment by arnaudvl** [comment]
Should be fine. It crashes I think because judging from the snippet you haven't defined `X_outlier` (the sequence you predicted outliers for) before. Although it should normally throw a `NameError` in that case, but maybe `X_outlier` was already defined at some point in your notebook? From the code you provided `X_outlier` would correspond to `data`.

Make sure as well that inferring the threshold makes sense for your application. E.g. from the [example in the docs](https://docs.seldon.io/projects/alibi-detect/en/latest/examples/od_sr_synth.html) I could assume there are roughly 10% outliers in the data. This obviously depends on the application, so be careful there.

**Comment by gireeshkbogu** [comment]
Does this mean I need to provide the outliers in advance? Isn't this an unsupervised model?

**Comment by arnaudvl** [comment]
You don't need to provide the outliers in advance. It would just help if you know roughly the expected % of outliers in a subset of your data which you can then use to estimate a threshold. So for instance your total number of instances in your sequence is 1e6 and you know that in a subset of 1e3 instances you have roughly 10% outliers but you have no idea about the rest, then you can pass those 1e3 instances to `infer_threshold` and pass 90 to the `threshold_perc` argument. You don't need to know exactly which instances in the 1e3 batch are outliers though. Alternatively, you can always inspect the outlier scores for your predictions which are stored in `od_preds['data']['instance_score']` and set a threshold yourself post hoc.

**Comment by gireeshkbogu** [comment]
This is very helpful. Thank you. I tried something like this and had the same error as before but with some results. 

```
data_2 = data_1.reset_index()
time_samples_1 = data_2['index'].values
time_samples = time_samples_1.reshape(-1, 1).astype(np.float32)

samples = data_2['temp'].values
data = samples.reshape(-1, 1).astype(np.float32)

od = SpectralResidual(
    threshold=None,  # threshold for outlier score
    window_amp=20,   # window for the average log amplitude
    window_local=20, # window for the average saliency map
    n_est_points=20  # nb of estimated points padded to the end of the sequence
)

data_train = data[:1000, :]
data_test = data[1000:1800]
print(data_train.shape, data_test.shape)

od.infer_threshold(data_train, time_samples, threshold_perc=99.995)
print('New threshold: {:.4f}'.format(od.threshold))

filepath = './'
save_detector(od, filepath)
od = load_detector(filepath)
od_preds = od.predict(data_test, time_samples, return_instance_score=True)

plot_feature_outlier_ts(od_preds,
                        data_test,
                        od.threshold,
                        #window=(1000, 1050),
                        t=time_samples,
                        X_orig=data)
```

<img width="1008" alt="Screen Shot 2020-07-02 at 11 38 25 AM" src="https://user-images.githubusercontent.com/3885659/86397375-91f33300-bc58-11ea-9607-4dd530f357ae.png">

**Comment by arnaudvl** [comment]
Can you try:

```python
plot_feature_outlier_ts(od_preds, data_test, od.threshold, window=(100, 150))
```
Because the `X_orig` kwarg does not apply in your case as you don't have a "clean" (no outliers) and "polluted" (noise injected in the clean data) time series. `t` can also be inferred automatically, so you should be able to ignore this.

**Comment by gireeshkbogu** [comment]
That seems to be working. Thank you! The only thing that is missing is my DateTime index. Is it possible to keep it so that I can use it on X-axis in the plot?

<img width="1028" alt="Screen Shot 2020-07-02 at 12 00 28 PM" src="https://user-images.githubusercontent.com/3885659/86399449-21e6ac00-bc5c-11ea-9f91-4c2f44763a44.png">

**Comment by arnaudvl** [comment]
Great! You might have to change the `plot_feature_outlier_ts` function to do so by replacing `ticks` with the relevant timestamps when calling `plt.plot`. E.g. [on this line](https://github.com/SeldonIO/alibi-detect/blob/master/alibi_detect/utils/visualize.py#L304) and [this line](https://github.com/SeldonIO/alibi-detect/blob/master/alibi_detect/utils/visualize.py#L322).

**Comment by gireeshkbogu** [comment]
The only part I am confused about is the SpectralResidual function. Does this use a sliding window of 20? (`window_amp=20,  window_local=20`). I will start reading the paper you referenced but it would be good to know your thoughts on this.

**Comment by arnaudvl** [comment]
Hopefully it is clear from the [docs](https://docs.seldon.io/projects/alibi-detect/en/latest/methods/sr.html) where the parameters are also described:

-  `window_amp` is the window used for the moving average in the spectral residual computation. The spectral residual is the difference between the log amplitude of the Fourier Transform and a convolution of the log amplitude over `window_amp`.

Then we apply the Inverse Fourier Transform to map the spectral residual sequence back from the frequency to the time domain. This sequence is called the saliency map. 

- `window_local`: window used for the moving average in the outlier score computation. The outlier score computes the relative difference between the saliency map and a moving average of the saliency map over `window_local` timesteps.

**Comment by gireeshkbogu** [comment]
Does this mean they always have to be a simailr number? For example, if I set `window_amp` to 20 then the `window_local `should be 20 as well?

**Comment by arnaudvl** [comment]
Yes that is correct. They don't have to be the same and the optimal window lengths will be application dependent. Low values will mainly reflect outliers wrt its neighbours and can lead to a more "noisy" outlier pattern.
