### ISSUE TITLE
Question regarding SpectralResidual

### ISSUE THREAD

**Issue by jlin-vt** [SeldonIO/alibi-detect#126]
Hi,
I have a question regarding `SpectralResidual ` function. I don't get the parameter `window_amp `, `window_local `, `n_est_points `.  Are they same as sliding window that was mentioned in the Microsoft paper? I assume SR is an online model. 

Also, is SR able to catch global, contextual and collective outliers? 

Thank you.

**Comment by arnaudvl** [comment]
Hi,

- `window_amp` is the window used for the convolution described in Eq.4 of the [paper](https://arxiv.org/abs/1906.03821). 

- `window_local` is used to compute the local average in Eq.7. 

- `n_est_points` are the number of estimated points described in Eq.8 and 9.

The parameters are also described in the [docs](https://docs.seldon.io/projects/alibi-detect/en/latest/methods/sr.html).

The method should be able to detect the different types of outliers in univariate time series data, assuming that you set your hyperparameters well so the windows etc capture the key statistics (e.g. periodicity, seasonality) of your data. This is of course easier said than done.

Hope this helps!
