### ISSUE TITLE
ad_ae_cifar10.ipynb results in Conv2D UnimplementedError

### ISSUE THREAD

**Issue by abuvaneswari** [SeldonIO/alibi-detect#127]
Hello,

My environment: centos 7, 1080 GTX GPUs, Anaconda 3, conda gcc and conda g++ version 7.3.0.

Python library versions:
absl-py==0.9.0
-e git+https://github.com/SeldonIO/alibi-detect.git@b99d81c8f36d2c863c29537944898ca545f704b3#egg=alibi_detect
argon2-cffi==20.1.0
astor==0.8.1
attrs==19.3.0
backcall==0.2.0
bleach==3.1.5
cachetools==4.1.1
certifi==2020.6.20
cffi==1.14.1
chardet==3.0.4
cloudpickle==1.1.1
cmdstanpy==0.4.0
convertdate==2.2.1
creme==0.6.1
cycler==0.10.0
Cython==0.29.21
dask==2.22.0
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
ephem==3.7.7.1
fbprophet==0.6
gast==0.2.2
google-auth==1.20.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.31.0
h5py==2.10.0
holidays==0.9.11
idna==2.10
imageio==2.9.0
importlib-metadata==1.7.0
ipykernel==5.3.4
ipython==7.17.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
jedi==0.17.2
Jinja2==2.11.2
joblib==0.16.0
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.6
jupyter-console==6.1.0
jupyter-core==4.6.3
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
korean-lunar-calendar==0.2.1
LunarCalendar==0.0.9
Markdown==3.2.2
MarkupSafe==1.1.1
matplotlib==3.3.0
mistune==0.8.4
mmh3==2.5.1
nbconvert==5.6.1
nbformat==5.0.7
networkx==2.4
notebook==6.1.1
numpy==1.19.1
oauthlib==3.1.0
opencv-python==4.3.0.38
opt-einsum==3.3.0
packaging==20.4
pandas==1.1.0
pandocfilters==1.4.2
parso==0.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.2.0
plotly==4.9.0
prometheus-client==0.8.0
prompt-toolkit==3.0.6
protobuf==3.12.4
ptyprocess==0.6.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
Pygments==2.6.1
PyMeeus==0.3.7
pyparsing==2.4.7
pyrsistent==0.16.0
pystan==2.18.0.0
python-dateutil==2.8.1
pytz==2020.1
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==19.0.2
qtconsole==4.7.5
QtPy==1.9.0
requests==2.24.0
requests-oauthlib==1.3.0
retrying==1.3.3
rsa==4.6
scikit-image==0.17.2
scikit-learn==0.23.2
scipy==1.5.2
Send2Trash==1.5.0
setuptools-git==1.2
six==1.15.0
tensorboard==2.0.2
tensorflow-estimator==2.0.1
tensorflow-gpu==2.0.0
tensorflow-probability==0.8.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
threadpoolctl==2.1.0
tifffile==2020.7.24
toolz==0.10.0
tornado==6.0.4
traitlets==4.3.3
urllib3==1.25.10
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
zipp==3.1.0

I tried to run ad_ae_cifar10.ipynb as is (Did not make any changes)

While executing the following 3 lines:
y_pred = predict_batch(clf, X_test, batch_size=32)
acc_y_pred = accuracy(y_test, y_pred)
print('Accuracy: {:.4f}'.format(acc_y_pred))

I got the error message in this attachment. 
[ad_error_message.txt](https://github.com/SeldonIO/alibi-detect/files/5052341/ad_error_message.txt)

**UnimplementedError: The Conv2D op currently only supports the NHWC tensor format on the CPU. The op was given the format: NCHW**

Please let me know how to resolve this issue.

**Comment by abuvaneswari** [comment]
Same error occurs in my MacBook as well. 
uname -a
Darwin M-C02XRDM5JG5H.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_6

Python3.7 Virtualenv with the Python libraries as listed in this attachment:
[ad_lib_mac.txt](https://github.com/SeldonIO/alibi-detect/files/5053635/ad_lib_mac.txt)

g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by arnaudvl** [comment]
The pretrained ResNet classification model used the format **NCHW** (*batch size, channels, height. width*) instead of the more common **NHWC** for TensorFlow. The **NCHW** format is supported for GPU but not CPU. This is why I added the note at the beginning of the notebook that it should be run with GPU enabled. You mentioned that you have a GPU in your environment but it seems it is not used (hence the error that the tensor format is not supported on CPU). So it could be a good idea to check why the GPU is not enabled?
