### ISSUE TITLE
How to train the od_vae_cifar10

### ISSUE THREAD

**Issue by LokLu** [SeldonIO/alibi-detect#140]
There is a pretrained outlier and adversarial detectors official released as 'od_vae_cifar10' under the example on https://docs.seldon.io/projects/alibi-detect/en/stable/examples/od_vae_cifar10.html.

However, if I train the detector from scratch on CIFAR10 dataset, I can't achieve similar results with the released weights.
Can you share some details about how he released weights are trained?

**Comment by arnaudvl** [comment]
Hi @LokLu , as far as I know I just followed the same notebook as you linked when I trained the model. When you try to reconstruct normal instances, do they look decent?

**Comment by LokLu** [comment]
I train from scratch. With my weights, the reconstruct instances look fine, except the perturbated symbols are not removed. But the official weights can remove the mask perfectly.

**Comment by arnaudvl** [comment]
So just to make sure I understand you: the masks (perturbations, e.g. visualized in cell 21 of [this notebook](https://docs.seldon.io/projects/alibi-detect/en/latest/examples/od_vae_cifar10.html#Visualize-outlier-scores-vs.-mask-sizes)) are also reconstructed?

**Comment by LokLu** [comment]
Yes, I add some fixed symbol as perturbation, but they can't be removed.

**Comment by arnaudvl** [comment]
And as a result the outlier score is not higher than for the in-distribution instances?

**Comment by LokLu** [comment]
I didn't check that, let me retry

**Comment by LokLu** [comment]
May I send my results to your email?

**Comment by arnaudvl** [comment]
If you wish you can also screenshot/copy paste them in here?
