### ISSUE TITLE
Possibly incorrect correction techniques used for Multi-variate drift detections

### ISSUE THREAD

**Issue by krishnajiraoh** [SeldonIO/alibi-detect#145]
The drift detection techniques of KSDrift & MMD aggregate the p-values of each feature either via the **Bonferroni** or the **False Discovery Rate** corrections. 

By definition, Bonferroni & FDR corrections are best situated when dealing with **dependent** multi-tests, i.e., hypothesis testing on multiple samples of a feature, wherein, the results of a test could be dependent on the previous ones.

However, in case of multi-variate data, the testing results of a feature are **independent** to those of the others, i.e., the features and hence their tests are independent. Hence, a suitable correction technique could be the **Fisher's method,** which combines the results from **several independent tests** bearing upon the same overall hypothesis (H0).

**Comment by jklaise** [comment]
Interesting point! However, I'm not sure I agree that the tests are independent because the features are not independent. You can think of each univariate test as checking whether there is a difference between the two datasets by comparing different features. As the number of features increases, it becomes more likely that we will detect a difference in at least one of the features by chance alone. I believe this is exactly the same setup as in a standard multiple comparison problem. Would you disagree?

**Comment by arnaudvl** [comment]
Also worth noting that the MMD detector is a direct multivariate test and does not require aggregating p-values.

**Comment by krishnajiraoh** [comment]
Hi jklaise,

I agree that "As the number of features increases, it becomes more likely that we will detect a difference in at least one of the features by chance alone". However, this is quite opposite to how FDR classifies a detection.

Lets take the following list of pvalues:
[ 0.01, 0.98, 0.84, 0.67 ]

Steps for FDR correction:
Sorted pvalues: [ 0.01 , 0.67, 0.84, 0.98 ]
Calculated qvalues: [0.0125, 0.025 , 0.0375, 0.05  ]
Is_drift : [ sorted_pvalues < qvalues ].any()

In deed, the FDR classifies the above list of pvalues as drifted because of the feature with pvalue 0.01. Whereas this low pvalue could be by chance.

**Comment by krishnajiraoh** [comment]
> Interesting point! However, I'm not sure I agree that the tests are independent because the features are not independent. You can think of each univariate test as checking whether there is a difference between the two datasets by comparing different features. As the number of features increases, it becomes more likely that we will detect a difference in at least one of the features by chance alone. I believe this is exactly the same setup as in a standard multiple comparison problem. Would you disagree?

Hi jklaise,

I agree that "As the number of features increases, it becomes more likely that we will detect a difference in at least one of the features by chance alone". However, this is quite opposite to how FDR classifies a detection.

Lets take the following list of pvalues:
[ 0.01, 0.98, 0.84, 0.67 ]

Steps for FDR correction:
Sorted pvalues: [ 0.01 , 0.67, 0.84, 0.98 ]
Calculated qvalues: [0.0125, 0.025 , 0.0375, 0.05 ]
Is_drift : [ sorted_pvalues < qvalues ].any()

In deed, the FDR classifies the above list of pvalues as drifted because of the feature with pvalue 0.01. Whereas this low pvalue could be by chance.
