### ISSUE TITLE
[question] Alibi Detect with TensorFlow Extended (TFX)

### ISSUE THREAD

**Issue by sazzouz** [SeldonIO/alibi-detect#159]
Hi. Love the package. I'm still fairly new to TensorFlow, in particular i am focusing on time series anomaly detection. Hoping to feed pipelines built with alibi detect with real network data to help identify odd behavior, hopefully streamed into an online model. My question: is it possible to deploy models built with alibi detect within a TFX pipeline? I know that alibi detect uses TF and Keras under the hood, so i can imagine this could work, however i am new to this area and i have not found any tutorials/questions about the live deployment of this package. Is TFX a good and viable approach to achieve this? Thanks a bunch and keep up the great work on this package, really appreciated.

**Comment by sazzouz** [comment]
Hi. As a follow up, more generally i am seeking guidance on production deployments of alibi-detect, even if this cannot involve TFX, perhaps KFServing is more appropriate. Is there any material that could be linked for this?  I've noticed that the 'integrations' module was removed in release v0.4.4 (2020-12-23), despite being mentioned in the readme. Please could you mention why this was and what alternative would be for integrating into production systems. Again, i appreciate your time and effort on this great library. Thank you.

**Comment by cliveseldon** [comment]
There are integrations in Seldon Core and KFServing.
 * Seldon Core
    * [Outlier detection](https://docs.seldon.io/projects/seldon-core/en/latest/analytics/outlier_detection.html)
    * [Drift detection](https://docs.seldon.io/projects/seldon-core/en/latest/analytics/drift_detection.html)
 * KfServing
    * [Outlier Detection](https://github.com/kubeflow/kfserving/tree/master/docs/samples/outlier-detection/alibi-detect/cifar10)
    * [Drift Detection](https://github.com/kubeflow/kfserving/tree/master/docs/samples/drift-detection/alibi-detect/cifar10)
