### ISSUE TITLE
Strange "NoneType object is not callable" error

### ISSUE THREAD

**Issue by gianpDomiziani** [SeldonIO/alibi-detect#160]
The KSDrift class returns "NoneType object is not callable" when it's trying to save the X_ref attributes.

As a test I passed a numpy.ndarray, passing False to the preprocess_X_ref option.
![ksdrift_error](https://user-images.githubusercontent.com/50718324/104926823-e8c81c00-59a0-11eb-9056-8428a4b834e0.png)

**Comment by Clusks** [comment]
What version are you on? I remember my version of alibi-detect I first used required me to declare a preprocessing function regardless of what I set `preprocess_X_ref` to, so I'd often just pass in to the `preprocess_fn` parameter the following function:

```
def fake_transform(X):
    return X

cd = KSDrift(
    p_val=0.05,
    X_ref=X,
    preprocess_X_ref=False,
    preprocess_fn=fake_transform,
    alternative='two-sided',
    data_type="tabular",
)
```

Could call the function whatever you want, it's just returning the same thing (so no actual pre-processing!) See if it manages to work using that.

**Comment by arnaudvl** [comment]
Hi @gianpDomiziani , could you just try if the following resolves your issue?

```python
cd = KSDrift(X_ref=NEID0_origin, preprocess_X_ref=False)
```

Which version of allibi-detect are you on?

**Comment by Clusks** [comment]
> 
> 
> Hi @gianpDomiziani , could you just try if the following resolves your issue?
> 
> ```python
> cd = KSDrift(X_ref=NEID0_origin, preprocess_X_ref=False)
> ```
> 
> @Clusks Defining a fake transform function should not be necessary anymore in a recent version of alibi-detect. :)

Oh yes, should mention updating the lib to the latest version will likely solve the problem as well!

**Comment by gianpDomiziani** [comment]
Yep, using preprocess_X_ref=False solved the issue. I guess it was because no model was available for preprocess_fn function. Thanks!
