### ISSUE TITLE
Chi-Squared and Mixed-type tabular data 

### ISSUE THREAD

**Issue by varunbanda** [SeldonIO/alibi-detect#167]
Hi,

The documentation shows 'Chi-Squared' and 'Mixed-type tabular data' drift detectors are still available. However, the alibi-detect package only has 'KSDrift' and 'MMDDrift'. 
1. I would like to know if the chisquare.py and tabular.py files available in the repository can be used? 
2. Is there any specific reason these two methods have been removed from 'alibi-detect'?
3. Is there any documentation/notebook example for detecting drift on tabular data using 'KSDrift' and 'MMDDrift'.

**Comment by arnaudvl** [comment]
Hi @varunbanda , the chi-squared and mixed-type tabular data drift detectors have only been added to the master branch last week and will be in the next release of the package late this week or early next week. You can already install alibi-detect from master to have access to both detectors right now or wait until the new version of the package is released. To answer your questions:

1. Yes, by installing from master. Check the [example in the docs](https://docs.seldon.io/projects/alibi-detect/en/latest/examples/cd_chi2ks_adult.html) for more details.
2. They've only just been added so will be included in the next release very soon.
3. There are no examples using `KSDrift` and `MMDDrift` on only tabular data (assuming with continuous numerical features), but the usage is very similar as with images and would follow the docs ([KSDrift](https://docs.seldon.io/projects/alibi-detect/en/latest/methods/ksdrift.html) and [MMDDrift](https://docs.seldon.io/projects/alibi-detect/en/latest/methods/mmddrift.html)):

```python
from alibi_detect.cd import KSDrift, MMDDrift

ks = KSDrift(p_val=0.05, X_ref=X_ref, correction='bonferroni')  # or e.g. with 'fdr' correction
preds_ks = ks.predict(X_test)

mmd = MMDDrift(p_val=0.05, X_ref=X_ref, n_permutations=1000)  # check docs for options to e.g. set kernel or dask acceleration
preds_mmd = mmd.predict(X_test)
```

**Comment by varunbanda** [comment]
Hi @arnaudvl . Thanks for the super quick response. I realized that those two tabular drift detection methods had been implemented only recently (I see that they got pushed 6 days ago), after I posted this question. Sorry for the confusion! 
Thanks for the code snippets regarding for KS and MMD drift detection methods.

May I know when the next version is slated for release?

**Comment by arnaudvl** [comment]
Hi @varunbanda , I'm aiming for Fri or early next week. Currently working on another classifier-based drift detector so the new release will significantly extend the drift detection capabilities.

**Comment by varunbanda** [comment]
That's sounds wonderful. Thanks!
