### ISSUE TITLE
Accessing records flagged as anomolous

### ISSUE THREAD

**Issue by sazzouz** [SeldonIO/alibi-detect#168]
Hi. I am using the seq2seq model to perform anomaly detection on time series data, largely following this tutorial here (https://docs.seldon.io/projects/alibi-detect/en/stable/examples/od_seq2seq_synth.html). In this demonstration, the anomalies are visualized  as a subplot alongside the original data (the plot after the confusion matrix and before the ROC curve plot). My question -  given that we understand where the anomalies occur and at what timestamp, is it possible to extract the timestamp indexes from the results of the anomalous points so that we can find these records in the original data? With this, i would then create a data-frame as a collection of such anomalous points and feed this into a classification model to perform intrusion detection. I assume this should be straight forward with the API you provided and will work for other time series models, i am just unable to figure this out at this point in time. Thank you.

**Comment by arnaudvl** [comment]
Hi @sazzouz , you should be able to retrieve the timestamp indices via `np.where(od_preds['data']['is_outlier'] == 1)` in the example.

**Comment by sazzouz** [comment]
Thanks for clarifying @arnaudvl . Just a follow up, for the multivariate data use case, how can one isolate the anomalies for a particular feature? As far as I can tell we only receive a one dimensional np.Array in the 'is_outlier' key in the od_preds dictionary. I have 13 features (i.e. columns) in my multivariate pandas dataframe with timestamps as the index.

**Comment by arnaudvl** [comment]
The outlier scores by feature are accessible as follows:

```python
preds = detector.predict(X, return_feature_score=True)
print(preds['data']['feature_score'])
```
You can also directly detect the outliers at the feature level:

```python
preds = detector.predict(X, outlier_type='feature')
print(preds['data']['is_outlier'])
```
