### ISSUE TITLE
TypeError: ks_2samp() got an unexpected keyword argument 'alternative'

### ISSUE THREAD

**Issue by sevmardi** [SeldonIO/alibi-detect#184]
hello, 
we are running against an error. We tried version 0.4.4 and the latest version as well. 

we have a simple setup as such

```
                cd = KSDrift(p_val=self._significance, X_ref=X_baseline, preprocess_X_ref=False)

                # Get ranked list of feature by drift (ranked by p-value)
                preds_h0 = cd.predict(X_target, return_p_val=True)
```
Except we get the following error 

```
Traceback (most recent call last):
 ...
  File "argus/components/drift_detection/drift_detector_exp2.py", line 301, in detect_drift_by_ID
    preds_h0 = cd.predict(X_target, return_p_val=True)

TypeError: ks_2samp() got an unexpected keyword argument 'alternative'
```

**Comment by arnaudvl** [comment]
Hi @sevmardi , it works fine for me. Which version of scipy are you using?

**Comment by arnaudvl** [comment]
I can see that old versions of scipy (I believe < 1.3) do not have the 'alternative' keyword argument. From 1.3 onwards it should be fine.

**Comment by sevmardi** [comment]
thanks for getting back to me so quickly! let me give it a quick try and update my scipy.

**Comment by sevmardi** [comment]
updating scipy seems to work. Thanks!
