### ISSUE TITLE
X_sample = od.dist_b.sample(n_sample).numpy() is very slow 

### ISSUE THREAD

**Issue by ingbeeedd** [SeldonIO/alibi-detect#192]
Why does this function take long?

**Comment by jklaise** [comment]
Are you using the PixelCNN model? How big is `n_sample` and what are the dimensions of the image? In general, since it's an autoregressive model sampling will be slow compared to other generative models.

**Comment by ingbeeedd** [comment]
@jklaise n_sample=4, dimensions of the image=128x128 

Sometimes I think I get caught in an infinite loop. And the question is, the pixelCNN model can't restore the DAGM dataset well, is there a reason?

**Comment by arnaudvl** [comment]
@ingbeeedd PixelCNN(++) is a likelihood-based method which might not restore the DAGM instances that well since it relies on fine-grained details.

**Comment by ingbeeedd** [comment]
Is pixel-cnn specialized in coarse grain method?

**Comment by arnaudvl** [comment]
It won't give you the most crisp images with fine attention to detail as seen in your specific dataset so might not be the most appropriate method. Check e.g. the original [PixelCNN++ paper](https://openreview.net/forum?id=BJrFC6ceg) samples.
