### ISSUE TITLE
Preprocessing functions and detector wrappers for common and principled use cases

### ISSUE THREAD

**Issue by ojcobb** [SeldonIO/alibi-detect#204]
Various drift detection strategies can be formulated as a combination of an existing drift detector (e.g ks or chi-squared) and a custom preprocessing step (often dependent on the deployed model of interest). We could avoid a lot of duplication and effort on behalf of users by providing implementations of these preprocessing steps and wrappers that call the corresponding preproc-test combinations. 

This issue is motivated by #197 and will encapsulate it by providing a wrapper for an MD3-like detector that accounts for drift into and out of areas of model uncertainty (the type of drift likely to cause degradation in model performance).

**Comment by arnaudvl** [comment]
This will be closely related to #220

**Comment by arnaudvl** [comment]
Similar to #220 is not exactly aligned anymore with our current thinking and can be closed.
