### ISSUE TITLE
Add more granular drift detectors

### ISSUE THREAD

**Issue by arnaudvl** [SeldonIO/alibi-detect#220]
Currently the drift detectors allow very flexible preprocessing steps to detect different types of drift. E.g. for predictive distribution shift in TensorFlow:

```python
from alibi_detect.cd.tensorflow import HiddenOutput, preprocess_drift

model = # TensorFlow model; tf.keras.Model or tf.keras.Sequential
preprocess_fn = partial(preprocess_drift, model=HiddenOutput(model, layer=-1), batch_size=128)

# initialise drift detector
cd = MMDDrift(x_ref, backend='tensorflow', p_val=.05, preprocess_fn=preprocess_fn)
```

We could however define more specific detectors, such as `PredictionMMDDrift` which already defines the above preprocessing step within the detector itself, so for the user it becomes something like:

```python
from alibi_detect.cd.tensorflow import HiddenOutput, preprocess_drift

model = # TensorFlow model; tf.keras.Model or tf.keras.Sequential
cd = PredictionMMDDrift(x_ref, model, backend='tensorflow', p_val=.05)
```

While this change is only small for the above example, it becomes much more significant for e.g. text drift using transformer embeddings. The more descriptive detector names should also make it easier for the user to identify which detector suits their use case best.

**Comment by arnaudvl** [comment]
This approach diverges from our current config-based workflow and therefore this issue can be closed I believe @jklaise @ascillitoe

**Comment by ascillitoe** [comment]
Yep agreed.
