### ISSUE TITLE
What to do as I am getting the P values as NAN on applying  Kolmogorov-Smirnov (K-S) tests for numerical columns

### ISSUE THREAD

**Issue by RitikaKulshresth** [SeldonIO/alibi-detect#221]
I have tried to run the the Kolmogorov-Smirnov (K-S) tests for numerical columns using the Categorical and mixed type data drift detection on income prediction dataset, for numerical features for ex ( Age, Capital Gain, Capital Loss, Hours per week) feature I am getting  K-S test value and P value as NAN but on applying the Chi-Square test on categorical features( Workclass, Education, Marital Status, Occupation, Relationship, Race, Sex, Country) I am getting the Chi2 and P value as some float values .
Please let me know shall I  try with the downgraded version of Alibi Detect  for running the  Categorical and mixed type data drift detection on income prediction file .
Looking for the resolution asap

**Comment by arnaudvl** [comment]
Hi @RitikaKulshresth , could you provide a reproducible example as well as the alibi-detect version you are using? Because I just ran the ChiSquareDrift and TabularDrift detectors using the latest release and they seem to run fine.

**Comment by RitikaKulshresth** [comment]
Hey @arnaudvl , I am running the example mentioned here: https://docs.seldon.io/projects/alibi-detect/en/stable/examples/cd_chi2ks_adult.html.
I am using the following versions:
alibi - 0.5.7
alibi_detect - 0.5.1
Python - 3.8.8

Getting the following output with continuous numerical features  as NAN
`Age -- Drift? No! -- K-S nan -- p-value nan
Workclass -- Drift? Yes! -- Chi2 18.114 -- p-value 0.020
Education -- Drift? No! -- Chi2 9.845 -- p-value 0.131
Marital Status -- Drift? No! -- Chi2 6.583 -- p-value 0.086
Occupation -- Drift? Yes! -- Chi2 17.900 -- p-value 0.022
Relationship -- Drift? No! -- Chi2 0.964 -- p-value 0.965
Race -- Drift? No! -- Chi2 1.168 -- p-value 0.883
Sex -- Drift? No! -- Chi2 0.463 -- p-value 0.496
Capital Gain -- Drift? No! -- K-S nan -- p-value nan
Capital Loss -- Drift? No! -- K-S nan -- p-value nan
Hours per week -- Drift? No! -- K-S nan -- p-value nan
Country -- Drift? Yes! -- Chi2 20.595 -- p-value 0.024`

**Comment by arnaudvl** [comment]
Thanks, could you upgrade to the latest alibi-detect (v0.6.0)? That should resolve the issue.

**Comment by RitikaKulshresth** [comment]
That issue worked fine. Thanks for your quick help. You can close this issue

Also I am trying to use the same ChiSquareDrift and TabularDrift detectors on Iris Dataset where we have only Continuous numerical features for that I am raising another new issue.
