### ISSUE TITLE
I am facing the issues while running the Kolmogorov-Smirnov (K-S) tests for the continuous numerical features data drift detection on iris dataset

### ISSUE THREAD

**Issue by RitikaKulshresth** [SeldonIO/alibi-detect#224]
I am facing the issues while running the Kolmogorov-Smirnov (K-S) tests for the continuous numerical features data drift detection on iris dataset .
For reference I have attached the code and Iris dataset ,below shared the Github link with you --https://github.com/RitikaKulshresth/Iris_Drift_Detection

Getting Error-
**ValueError: The internally computed table of expected frequencies has a zero element at (0, 0).**

`

`

**Comment by yanhong-zhao-ef** [comment]
I think this error is returned by the Chi-squared test - just had a look at your script and you might be using the API wrong. Category features are for categorical variables.

Can you show us the full stack trace as to which function raised this error?

**Comment by RitikaKulshresth** [comment]
Thanks @yanhong-zhao-ef for looking into it. The error is coming from chi2_contingency method in contingency.py.
However, I am trying to run the K-S tests only for continuous numerical features.
Adding the stack trace:

> Traceback (most recent call last):
  File ".\iris_drift_detection.py", line 72, in <module>
    preds = cd.predict(X_t0)
  File "C:\Users\rkulshre\Outlier Detection\test_env\lib\site-packages\alibi_detect\cd\base.py", line 495, in predict      
    p_vals, dist = self.score(x)
  File "C:\Users\rkulshre\Outlier Detection\test_env\lib\site-packages\alibi_detect\cd\base.py", line 466, in score        
    score, dist = self.feature_score(x_ref, x)  # feature-wise univariate test
  File "C:\Users\rkulshre\Outlier Detection\test_env\lib\site-packages\alibi_detect\cd\tabular.py", line 121, in feature_score
    dist[f], p_val[f], _, _ = chi2_contingency(contingency_table)
  File "C:\Users\rkulshre\Outlier Detection\test_env\lib\site-packages\scipy\stats\contingency.py", line 252, in chi2_contingency
    raise ValueError("The internally computed table of expected "
ValueError: The internally computed table of expected frequencies has a zero element at (0, 0).

**Comment by yanhong-zhao-ef** [comment]
then I think you don't need to pass in a feature dict like the one in your py file:
```
categories_per_feature = {0: None, 1: None, 2: None, 3: None}
```
that option is for computing how many categories are present in categorical data columns not continuous data columns

**Comment by arnaudvl** [comment]
@yanhong-zhao-ef 's comment is correct. `categories_per_feature = {0: None, 1: None, 2: None, 3: None}` indeed means that features 0, 1, 2 and 3 are categorical but you just want to infer the categories of those features from the reference data. If you just keep `categories_per_feature=None` (the default) that should fix your issues.

**Comment by RitikaKulshresth** [comment]
Thanks for your quick help .You can close this issue
