### ISSUE TITLE
Show impact of std_clip for Mahalanobis outlier detector

### ISSUE THREAD

**Issue by arnaudvl** [SeldonIO/alibi-detect#23]
The std_clip parameter makes the mean and covariance updates more stable. This can be important when the outliers arrive in batches instead of e.g. uniform. The effect is already visualized in https://github.com/SeldonIO/seldon-core/blob/master/components/outlier-detection/mahalanobis/doc.ipynb.

**Comment by FlorianDejax** [comment]
@arnaudvl does this impct is expected to be added to this notebook?
https://github.com/SeldonIO/seldon-core/blob/master/components/outlier-detection/mahalanobis/doc.ipynb.

Does the plots showing the impact of `std_clip` are expected to be placed in the folder `images`?

**Comment by arnaudvl** [comment]
@FlorianDejax : the idea is to show the plots visualising the impact of clipping from https://github.com/SeldonIO/seldon-core/blob/master/components/outlier-detection/mahalanobis/doc.ipynb in https://github.com/SeldonIO/alibi-detect/blob/master/examples/od_mahalanobis_kddcup.ipynb.  The images should just be generated when running the notebook, so no need to place the saved images in a folder.

**Comment by arnaudvl** [comment]
Dealt with in outlier revamp
