### ISSUE TITLE
Factor out backend (eg PyTorch, TensorFlow) validation.

### ISSUE THREAD

**Issue by arnaudvl** [SeldonIO/alibi-detect#230]
Add `_validate_backend` functionality instead of checking on the fly as in https://github.com/SeldonIO/alibi-detect/blob/master/alibi_detect/cd/classifier.py#L98.

**Comment by amanjha8100** [comment]
I would like to solve this issue. I am new to open source therefore If I make any mistakes please do guide me.

**Comment by jklaise** [comment]
@amanjha8100 for sure! The most appropriate place for this function seems to be https://github.com/SeldonIO/alibi-detect/blob/master/alibi_detect/utils/frameworks.py. The function should take `backend` string provided by the user and validate it pretty much the same way as these lines: https://github.com/SeldonIO/alibi-detect/blob/13b2664dca601aebc25c774fd6814bd5d380d6e7/alibi_detect/cd/classifier.py#L97-L102 It would also be useful to define a `BACKENDS=['tensorflow', 'pytorch']` constant in this module.

@arnaudvl we may need additional functionality in the future, e.g. if some methods implement one backend but not the other.

**Comment by amanjha8100** [comment]
I will try to solve this issue. Thank you for the guidance.

**Comment by ascillitoe** [comment]
This issue will be solved by #537.
