### ISSUE TITLE
Integration of Online Drift Detectors

### ISSUE THREAD

**Issue by ojcobb** [SeldonIO/alibi-detect#235]
We are looking to integrate some detectors which operate in an online/sequential manner, testing for drift at every time-step with overlapping windows. This is contrast to our existing 'offline' detectors for which batches (assumedly disjoint and large) of test instances are passed to the `predict` method for each test.

Although online detectors will require underlying functionality that differs from offline equivalents, the interface can remain the same. The main difference would be that the `predict` method would expect a single instance rather than a batch. Usually a p-value would not be returned with each call, just an indication of whether the test-statistic (continually updated at low-cost) exceeds a (possibly time-dependent) threshold computed during a configuration phase. The trajectory of this test-statistic will likely be of interest for monitoring and debugging etc.

Given the difference in how online and offline detectors will be used we need to decide the best way for them to coexist. Three possible options are

1. Continue creating a new module for each detector within the `alibi_detect.cd` subpackage and differentiate online and offline detectors via naming conventions.
2. Create a new `alibi_detect.cd.online` subpackage that hosts all online detectors and associated functionality.
3. Allow 'online' or 'offline' to be specified as an argument to a higher level interface in a manner analogous to the specification of 'tensorflow' or 'pytorch' backend. 

An initial discussion suggested that option 1 is probably most suitable. Option 2 could lead the package structure to become too deep given additional `.pytorch` and `.tensorflow` directories would also be required. Option 3 could lead to an abundance of arguments that are only relevant for certain combinations of online/offline, tensorflow/pytorch etc. Moreover, whilst the first online detectors we plan to integrate have offline equivalents (based on MMD/LSDD metrics) this might not be the case for all future online detectors.

**Comment by arnaudvl** [comment]
#245
