### ISSUE TITLE
Change PCA preprocessing step

### ISSUE THREAD

**Issue by arnaudvl** [SeldonIO/alibi-detect#247]
Fit on reference data, project test batch.

**Comment by ojcobb** [comment]
I'd consider the recommended workflow for PCA preprocessing to be fitting a PCA object on a split of reference data which then has a `call` method that projects new data onto the PCs. This object could then be passed as the `preprocess_fn` argument.

However this can be implemented as:
```
from sklearn.decomposition import PCA
pca = PCA(n_components)
pca.fit(x_split)
preprocess_fn = pca.transform
```

The only possible way I can see of simplifying this any further is providing a wrapper `cd.PCA` that has a `__call__()` method that calls `transform()`. The above could then be implemented as:
```
from alibi_detect.preprocess import PCA
pca = PCA(n_components)
pca.fit(x_split)
preprocess_fn = pca
```

I'm not sure this is worth implementing. I think we'd be better off just providing an example of how to use `sklearn.decomposition.PCA`? @arnaudvl

**Comment by arnaudvl** [comment]
Sounds good, feel free to add as an example to one of the existing example notebooks. The PCA preprocessing step is mentioned in various locations across the notebooks, so best to update those mentions as well as it doesn't come with the library anymore.

**Comment by arnaudvl** [comment]
#284
