### ISSUE TITLE
Update type hints for tensorflow functions that we pass numpy inputs

### ISSUE THREAD

**Issue by ojcobb** [SeldonIO/alibi-detect#253]
Because tensorflow functions accept numpy inputs we often don't bother to make the conversions but then the type hints are misleading. So we should update type hints to acknowledge fact numpy inputs are also fine.

**Comment by tim5go** [comment]
@ojcobb 
Can I give a try on this issue?

**Comment by ojcobb** [comment]
Hi @tim5go, that would be great.

An example of what I was referring to is 
https://github.com/SeldonIO/alibi-detect/blob/a2fc6125eaf8d15068a3069e64d8fbc9cd1b41cb/alibi_detect/cd/tensorflow/mmd.py#L84-L86
where you can see `x` and `y` may be numpy arrays but the default kernel `GaussianRBF` is typed to operate only on tensorflow tensors.

There will likely be many places with similar inconsistencies. Let me know if I can advise further.

**Comment by tim5go** [comment]
@ojcobb 
Thanks, your example is very clear!
Let me work on it. I will create a PR very soon.

**Comment by ojcobb** [comment]
This problem wasn't as widespread as first thought. On reflection the benefit of updating the type hints for the small number of tensorflow functions we pass numpy inputs probably doesn't outweigh the cost of either breaking consistency of type hints between different tensorflow functions or using `Union[tf.Tensor, np.ndarray]` everywhere.
