### ISSUE TITLE
I am not getting the ClassifierUncertaintyDrift and RegressorUncertaintyDrift on installing the alibi and alibi-detect library

### ISSUE THREAD

**Issue by RitikaKulshresth** [SeldonIO/alibi-detect#254]
I am using the below versions  for alibi but still I am not getting the  ClassifierUncertaintyDrift and RegressorUncertaintyDrift  on Jupyter Hub

!pip install alibi==0.5.8
!pip install alibi-detect==0.6.2

alibi_detect.cd.__all__
Getting the output -->
'ChiSquareDrift', 'ClassifierDrift', 'KSDrift', 'MMDDrift', 'TabularDrift'

**Comment by arnaudvl** [comment]
I tried to replicate your error but all seems fine for me. I pip installed the same alibi and alibi-detect versions in a clean conda environment (python 3.7) and get:

```
import alibi_detect
print(alibi_detect.cd.__all__)

['ChiSquareDrift', 'ClassifierDrift', 'KSDrift', 'MMDDrift', 'TabularDrift', 'ClassifierUncertaintyDrift', 'RegressorUncertaintyDrift']

print(alibi_detect.__version__)

'0.6.2'
```

**Comment by RitikaKulshresth** [comment]
Thanks for quick reply and help I am using python 3.8 version ,just now checked with Python version-3.7 ,it is working fine.
Good to close the issue
