### ISSUE TITLE
Support updating reference data for LSDD detector

### ISSUE THREAD

**Issue by ojcobb** [SeldonIO/alibi-detect#261]
During initialisation the lsdd detector (`alibi_detect/cd/lsdd.py`) performs normalisation of the reference data `x_ref`. When `update_x_ref` is not `None` unnormalized data is being integrated alongside normalized data which is incorrect and is causing problems. The integration of the data takes part within the base class which doesn't allow for additional normalisation steps. 

There may be a workaround involving overriding `self.preprocess_fn` with a new function `lambda x: self._normalize(self.preprocess_fn(x))`.

**Comment by arnaudvl** [comment]
#263
