### ISSUE TITLE
Load detector error when KSDrift has no model

### ISSUE THREAD

**Issue by uzi0espil** [SeldonIO/alibi-detect#267]
When loading a stored `KSDrift`, or any of the following: `['ChiSquareDrift', 'ClassifierDriftTF', 'KSDrift', 'MMDDriftTF', 'TabularDrift']`.  the method will raise error: `Directory /path/to/directory/model does not exist`

This due that tf model is assumed to always been there as stated in this line of code:

https://github.com/SeldonIO/alibi-detect/blob/a2fc6125eaf8d15068a3069e64d8fbc9cd1b41cb/alibi_detect/utils/saving.py#L1019

To reproduce,

~~~python
import numpy as np

from alibi_detect.cd import KSDrift
from alibi_detect.utils.saving import save_detector, load_detector

X_ref = np.random.normal(loc=0, scale=1, size=10000)
X_new = np.random.normal(loc=5, scale=10, size=100)

cd = KSDrift(X_ref, p_val=0.05)
cd.predict(X_new, return_p_val=True, return_distance=True)

filepath = "path/to/your/folder"
save_detector(cd, filepath)
cd = load_detector(filepath)

~~~

**Comment by arnaudvl** [comment]
With error do you mean warning? Because I ran the code snippet and it works fine for me. This is the line where the warning will be thrown:

https://github.com/SeldonIO/alibi-detect/blob/a2fc6125eaf8d15068a3069e64d8fbc9cd1b41cb/alibi_detect/utils/saving.py#L1069

**Comment by uzi0espil** [comment]
Yes you are right, this was just a warning, I don't know I thought that `cd` was already initialized from the first initialization and not re-loaded from the `load_detector`, I think I need a cup of coffee.
