### ISSUE TITLE
Conversion of OutlierAE into the TensortRT engine file

### ISSUE THREAD

**Issue by Abhinav-Anil** [SeldonIO/alibi-detect#279]
I have trained the OutlierAE model using alibi detect and have achieved good results. I want to run this model on a jetson device and wish to convert the model into a TensorRT engine file. What are the steps to do this?  @ahousley @tchellam @tchellam @clauslundholm

**Comment by michaelcheah** [comment]
@Abhinav-Anil 

It would probably be easiest to convert your models into ONNX models. From there, it should be possible to convert your ONNX files to TensorRT engine files. Here are some links that might be useful
* https://github.com/onnx/onnx-tensorrt
* https://learnopencv.com/how-to-convert-a-model-from-pytorch-to-tensorrt-and-speed-up-inference/

The backend for alibi-detect models uses either tensorflow and pytorch. There should be tools that allow you to convert them into ONNX models. Hope that helps!
