### ISSUE TITLE
Add image example AEGMM outlier detector

### ISSUE THREAD

**Issue by arnaudvl** [SeldonIO/alibi-detect#31]

**Comment by mishinma** [comment]
Hi @arnaudvl. I'm using alibi-detect in my master's thesis and I would like to contribute to the project. This seems like a good place to start as I want to play around with aegmm anyway. Should the notebook be similar to the cifar10 vae example?

**Comment by arnaudvl** [comment]
Cool! Yes, the notebook could be similar to the CIFAR10 VAE one, leveraging the same utility functions.  It might take some experimenting getting the latent dimension and the number of components in the GMM right. Don't hesitate to reach out if you have questions on either of those. Another interesting part of the algorithm to look at would be ```recon_features```, the function to extract features from the reconstructed instance by the decoder. The default is the built in ```eucl_cosim_features``` function, but it is likely that there are better feature extraction functions for higher dimensionalities like images.
