### ISSUE TITLE
Fix various embedded images across notebooks

### ISSUE THREAD

**Issue by arnaudvl** [SeldonIO/alibi-detect#313]
E.g. https://docs.seldon.io/projects/alibi-detect/en/latest/examples/cd_online_camelyon.html or https://docs.seldon.io/projects/alibi-detect/en/latest/examples/alibi_detect_deploy.html.

**Comment by ascillitoe** [comment]
@arnaudvl I have a fix for this in the latest doc updates, I'll include it in the main commit for those updates.
