### ISSUE TITLE
how to decide which drift detector should be used in tabular data

### ISSUE THREAD

**Issue by dishan14** [SeldonIO/alibi-detect#372]
how do i choose between drift detectors in classification and regression tabular data, which detector would be best for me

**Comment by Srceh** [comment]
> Hi @jklaise, thank you for your prompt reply. yes, my data consists of both type of features and I need to detect drift in input data. I had few more doubts regarding the same.
> 
> 1. are drift detection methods like LSDD,MMD also good for detecting drift in tabular input data.
> 2. in case if I want to detect drift in model predictions then which method should I choose.
> 3. is there any metric for comparing performance of drift detection methods.

1. As long as you apply adequate pre-processing steps to the data, both methods should work reasonably well. (i.e. apply one-hot encoding to nominal features, possibly also run a PCA / autoencoder).

2. Assume your model can output uncertinties on the prediction (i.e. probability vectors in classification), you can directly apply methods from https://docs.seldon.io/projects/alibi-detect/en/latest/cd/methods/modeluncdrift.html .

3. The most common metrics are type-1 (false positive / detect false drift ) and type-2 (false negative /  not detect occurred drfit) errors.
