### ISSUE TITLE
Question: Does this repo include smoothing?

### ISSUE THREAD

**Issue by BrandonKMLee** [SeldonIO/alibi-detect#374]
Referencing https://github.com/cerlymarco/tsmoothie

**Comment by arnaudvl** [comment]
Not sure what you mean with *smoothing* exactly but the the repo contains outlier detection techniques for time series such as the [Prophet](https://docs.seldon.io/projects/alibi-detect/en/latest/od/methods/prophet.html), [Spectral Residual](https://docs.seldon.io/projects/alibi-detect/en/latest/od/methods/sr.html) and [Seq2Seq](https://docs.seldon.io/projects/alibi-detect/en/latest/od/methods/seq2seq.html) detectors. The first 2 compare an instance with some form of smoothed historical version, so could fall under your definition of smoothing.
