### ISSUE TITLE
Can't run Spectral Residual 

### ISSUE THREAD

**Issue by ayushpatidar** [SeldonIO/alibi-detect#382]
I have trying to run the infer_threshold function of Spectral Residual  but i am getting following error.

ufunc 'true_divide' cannot use operands with types dtype('float64') and dtype('<m8[ns]')

code:
od.infer_threshold(
    df[['y']].values,
    t=np.array(df['ds'].values)
 
)

>>> print( df[['y']].values.shape)
(1000,1)

>>> print(df[['y']].values.type)
numpy.ndarray

>>> print(np.array(df['ds']).shape)
(1000,)

>>> print(np.array(df['ds']).type)
numpy.array

 the data type of ds is : datetime64[ns]

Please provide the Documentation about the format of the input to pass in the function.

**Comment by ascillitoe** [comment]
Hi @ayushpatidar, @arnaudvl is more familiar with the `SpectralResidual` detector and may be able to help more with this, but I suspect your issue might be that `infer_thresholds` expects `t` to be a numpy `int` array of time-steps i.e. np.array([1,2,3,4,5]), not actual `datetime`'s. 

What does your time data look like? If it is uniform (i.e. constant dt) you should actually be able to leave `t` out and `infer_threshold` will do `t = np.arange(X.shape[0])` internally. If your missing some timesteps but your datatime data is still simple, you might be OK with `np.array(df['ds'].values.astype(int)`. If your data is more complex and spans multiple hours/days/weeks etc this might require a little more thought. 

Re documentation, thanks for pointing out that a description of `t` is missing from the `infer_threshold` docstring, I'm labelling this issue as "docs" and will keep this open to address that. This also highlights that we could do with more granular type hints for np.ndarrays (i.e. what dtype), so I'll open another issue for that.

**Comment by RobertSamoilescu** [comment]
Timestamp documentation was missing. It is now included in #396 .

**Comment by ascillitoe** [comment]
@RobertSamoilescu, can we close this now?
