### ISSUE TITLE
Modular package

### ISSUE THREAD

**Issue by candalfigomoro** [SeldonIO/alibi-detect#388]
The alibi-detect package requires a lot of very heavy dependencies (opencv, tensorflow). It could be that I only need the `TabularDrift` class and I don't need opencv/tensorflow/pytorch for that. Would it be possible to make those dependencies optional (like the "prophet" one), so we can use some simple detectors without requiring both opencv and tensorflow? Thanks

**Comment by jklaise** [comment]
Hi @candalfigomoro! This is something that's definitely on our radar, we want to modularize the dependencies and allow the library to be installed with bare-bones dependencies by default and handle the cases where missing dependencies prohibit use of more advanced features more gracefully. It will take some time to design the right structure for this as we may also need to refactor some parts of the library, but we're hoping to start to work on this very soon.

**Comment by ascillitoe** [comment]
Resolved by #537, #538, #539, #541 and #542.
