### ISSUE TITLE
I found some critical errors while running cd_ks_cifar10.ipynb example.

### ISSUE THREAD

**Issue by KevinRyu** [SeldonIO/alibi-detect#421]
Hi,

Thanks for serving this library for public first.
As I write down the title, I met some errors in that example.
Would you cross check this errors? Would you please guide how to solve errors?
Please evaluate this errors and If these are correct errors,
update next release as possible.

1. url makes error in windows os
    Reason: os.join.path append delimiter "\\". This conflicts with hard coded url 
    including slash delimiter. --> I modified url by myself. Please check this and fix 
    next release.

2. from alibi_detect.utils.prediction import predict_batch is not fixed in this example.
    I also modified function call like y_pred = predict_batch(X_test, clf, batch_size=256)

3. Dimension of inputs to compare is different. So, this makes errors in accuracy 
    function. (bool has attribute astype)

 def accuracy(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    print(y_true.shape, y_pred.shape)
    return (y_true == y_pred).astype(int).sum() / y_true.shape[0]

Result:
   
Severity: 1 of 5
Loading corrupted dataset...
Preprocess data...
Make predictions on corrupted dataset...
Compute adversarial scores on corrupted dataset...
Get labels for malicious corruptions...
(190000,) (190000, 10)   --> Dimension is different
/tmp/ipykernel_7443/1830851723.py:38: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  idx_orig_right = np.where(y_pred_repeat == y_corr)[0]
/tmp/ipykernel_7443/1830851723.py:39: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  idx_corr_wrong = np.where(y_pred_corr != y_corr)[0]
/tmp/ipykernel_7443/1830851723.py:45: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  idx_corr_right = np.where(y_pred_corr == y_corr)[0]
/tmp/ipykernel_7443/1515427434.py:3: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  return (y_true == y_pred).astype(int).sum() / y_true.shape[0]

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_7443/1830851723.py in <module>
     49     score_drift[s]['harm'] = score_corr[idx_harmful]
     50     score_drift[s]['noharm'] = score_corr[idx_harmless]
---> 51     score_drift[s]['acc'] = accuracy(y_corr, y_pred_corr)

/tmp/ipykernel_7443/1515427434.py in accuracy(y_true, y_pred)
      1 def accuracy(y_true: np.ndarray, y_pred: np.ndarray) -> float:
      2     print(y_true.shape, y_pred.shape)
----> 3     return (y_true == y_pred).astype(int).sum() / y_true.shape[0]

AttributeError: 'bool' object has no attribute 'astype'

4. I needed to run " load_pretrained = false condition" because model download fail. 
   (upper url and os.join.path in windows 10) But I found errors in model code.
   Some library is not imported. So, I can't run Conv2DTranspose, AdversarialAE 
   functions.

5. Timeout=2 makes download error in request.get depending on the network environment. So, I removed this. 

That's all.

**Comment by ascillitoe** [comment]
Hi Kevin, thank you for raising these issues, we're going to add CI tests for the Windows OS (https://github.com/SeldonIO/alibi-detect/issues/422), and will address the Windows related issues above as part of that. Re any remaining issues I will get back to you shortly.

**Comment by ascillitoe** [comment]
Hi Keven, re the above, the soon-to-be-merged #423 should fix the above issues in the notebook. Responding to your five issues in more detail:

1. As you highlighted, `os.path.join` is particularly well suited to joining url's in Windows. We've removed `os.path.join` from the code base entirely, and now use a custom `alibi_detect.utils.fetching.join_url` instead. 
2. `predict_batch` has been refactored to be backend specific. The import has been corrected accordingly. The `return_class` kwarg in `predict_batch` is also now depreciated (and the order of `X` and `model` is swapped). `return_class=True` used to take predictions and run `.argmax(axis=1)` over them in order to obtain class predictions. This should now be done manually instead (e.g. see [here](https://docs.seldon.io/projects/alibi-detect/en/latest/examples/ad_ae_cifar10.html#Load-classifier)). We missed this update from three notebooks (including `cd_ks_cifar10`), which have now been updated.
3. Once the `argmax(axis=1)` has been added to `y_pred = ...`, the dimensions should line up.
4. The missing imports have been added.
5. We've increased the timeout from 2 to 5 seconds, which should hopefully be more friendly to slower networks.

**Comment by KevinRyu** [comment]
Hi, Ashley

First of all, I really appreciate your support. I just modified some code
lines including hardcoding even though
I already modified some related codes and did run successfully. Anyway, I
think someone who is using this library needs the updated library.

   1. As you highlighted, os.path.join is particularly well suited to
   joining url's in Windows. We've removed os.path.join from the code base
   entirely, and now use a custom alibi_detect.utils.fetching.join_url instead.
   *---> I hope this solves the path problem. Thanks.*
   2. predict_batch has been refactored to be backend specific. The import
   has been corrected accordingly. The return_class kwarg in predict_batch is
   also now depreciated (and the order of X and model is swapped).
   return_class=True used to take predictions and run .argmax(axis=1) over
   them in order to obtain class predictions. This should now be done manually
   instead (e.g. see here
   <https://docs.seldon.io/projects/alibi-detect/en/latest/examples/ad_ae_cifar10.html#Load-classifier>).
   We missed this update from three notebooks (including cd_ks_cifar10),
   which have now been updated. *---> I added one line code to the next
   line of predict_batch. y_pred = np.array([data.argmax() for data in
   y_pred]). This solved all the dimension problems in this example. Anyway,
   I'm gonna check the upper link of what you wrote. Thanks*
   3. Once the argmax(axis=1) has been added to y_pred = ..., the
   dimensions should line up. *---> Nice!*
   4. The missing imports have been added. *---> Thanks. This is a minor
   one.*
   5. We've increased the timeout from 2 to 5 seconds, which should
   hopefully be more friendly to slower networks. *---> I hope npy files
   can be loaded from the local download directory if the user executes the
   download code once. I just remark "try catch" code for request.get(url) and
   modify npy load function's argument. What do you think about this?*

Thank you very much.

That's all.

2022년 1월 13일 (목) 오후 10:03, Ashley Scillitoe ***@***.***>님이 작성:

**Comment by ascillitoe** [comment]
@KevinRyu re your last point about caching the datasets when fetched, that seems like a nice idea. We do something similar for `fetch_tf_model` and `fetch_detector` already (as under-the-hood they use `tf.keras.models.load_model` and `tf.keras.utils.get_file`), but don't have this capability for the dataset fetching utilities. 

We are planning to somewhat overhaul the fetching utilities in the future, but it isn't at the top of our priority list. Its a good idea though so please do feel free to open a feature request issue, or even a PR! 🙂

**Comment by KevinRyu** [comment]
Thanks for the feedback!

2022년 1월 13일 (목) 오후 11:05, Ashley Scillitoe ***@***.***>님이 작성:
