### ISSUE TITLE
Run CI tests on Windows and MacOS platforms

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/alibi-detect#422]
In light of #411 it makes sense to extend our CI test suite to run on non-Linux platforms. To avoid 3x-ing the workload it may be useful to see if we can just run these on the latest supported Python version (3.9 right now).

**Comment by ascillitoe** [comment]
https://github.com/SeldonIO/alibi-detect/issues/421 is also related. I'll set up the CI and hopefully that will expose any other issues.
