### ISSUE TITLE
Backend parameter in ClassifierDrift function error in cd_clf_audult.ipynb example.

### ISSUE THREAD

**Issue by KevinRyu** [SeldonIO/alibi-detect#433]
Hi,

I got an error at backend argument in ClassifierDrift function.
I saw the issue about this. So, I thought sklearn backend is already supported.
Am I wrong? How can I run this code?

Error messages:

      3 
      4 # define drift detector with binarize prediction
----> 5 detector = ClassifierDrift(
      6     x_ref=x_ref,
      7     model=model,

~\Miniconda3\envs\alibidet\lib\site-packages\alibi_detect\cd\classifier.py in __init__(self, x_ref, model, backend, p_val, preprocess_x_ref, update_x_ref, preprocess_fn, preds_type, binarize_preds, reg_loss_fn, train_size, n_folds, retrain_from_scratch, seed, optimizer, learning_rate, batch_size, preprocess_batch_fn, epochs, verbose, train_kwargs, device, dataset, dataloader, data_type)
    117                               f'ClassifierDrift detector with {backend} backend.')
    118         elif backend not in ['tensorflow', 'pytorch']:
--> 119             raise NotImplementedError(f'{backend} not implemented. Use tensorflow or pytorch instead.')
    120 
    121         kwargs = locals()

NotImplementedError: sklearn not implemented. Use tensorflow or pytorch instead.

**Comment by jklaise** [comment]
@KevinRyu the functionality has been recently merged but we haven't done a new stable release. We will release version `0.8.1` in the next few days, in the meantime to get the new functionality you could install from `master`:

```
pip install git+https://github.com/SeldonIO/alibi-detect.git
```

**Comment by KevinRyu** [comment]
Thanks for your feedback. I will wait next release.

2022년 1월 18일 (화) 오후 6:25, Janis Klaise ***@***.***>님이 작성:

**Comment by ascillitoe** [comment]
@KevinRyu version v0.8.1 has now been released. Once installed, this should allow you to use `backend='sklearn'`. 🙂

**Comment by KevinRyu** [comment]
Awesome, thanks!

2022년 1월 19일 (수) 오전 2:10, Ashley Scillitoe ***@***.***>님이 작성:
