### ISSUE TITLE
Can the SpectralResidual and Prophet implementations in Alibi-Detect handle multivariate timeseries?

### ISSUE THREAD

**Issue by jayrmh** [SeldonIO/alibi-detect#446]
Hello! This is a fantastic library for anomaly detections. I may have missed any notebooks or previous inquiries on this matter, but I would like to know if SpectralResidual and Prophet (not in general, but in the case of this library only) can handle multivariate time-series data. So given a, b, c and x, I want the model to reconstruct only x.

Kindly let me know, thank you!
JR

**Comment by arnaudvl** [comment]
Hi @jayrmh , thanks for the kind words. SpectralResidual and Prophet in Alibi Detect deal with univariate time series. For multivariate time series, you could try the [Seq2Seq detector](https://docs.seldon.io/projects/alibi-detect/en/latest/od/methods/seq2seq.html). This detector can then also provide outlier scores for each feature in your multivariate data. Check [this example notebook](https://docs.seldon.io/projects/alibi-detect/en/latest/examples/od_seq2seq_synth.html) for more info.
