### ISSUE TITLE
Method to save OnlineDriftDetector

### ISSUE THREAD

**Issue by GeorgeWu97** [SeldonIO/alibi-detect#455]
The document has provided methods to save OfflineDriftDetector like the following
```
from alibi_detect.utils.saving import save_detector

filepath = './my_detector/'
save_detector(cd, filepath)
```
however, when saving OnlineDriftDector, errors would occur like 

>  CVMDriftOnline is not supported by `save_detector`. 

Is there any method to save OnlineDriftDector safely?

**Comment by ascillitoe** [comment]
This has been addressed since [v0.10.0](https://github.com/SeldonIO/alibi-detect/releases/tag/v0.10.0).
