### ISSUE TITLE
Benchmark different detection algorithms

### ISSUE THREAD

**Issue by arnaudvl** [SeldonIO/alibi-detect#48]
Benchmark outlier and adversarial detection algorithms across datasets covering at least tabular (numerical/categorical features and low/high dimensionality), image and time series datasets.

**Comment by jklaise** [comment]
The drift detection benchmarking is currently in progress, outlier detection will be defined as part of defining the outlier detection roadmap.

**Comment by arnaudvl** [comment]
This will be an external project so can close this issue @jklaise @ascillitoe ?
