### ISSUE TITLE
Cannot save trained od

### ISSUE THREAD

**Issue by aaronrmm** [SeldonIO/alibi-detect#488]
## Summary
Updating /doc/source/examples/od_vae_adult.ipynb lets me train and predict, but errors on saving new model.

## Details
This may be a duplicate of https://github.com/SeldonIO/alibi-detect/issues/323.
I was using the od_vae_adult notebook because it is the closest example for my needs. After installing via `pip install alibli_detect`, pycharm identifies `from tensorflow.keras.layers import Dense, InputLayer` is not valid because tensorflow.keras is no longer a package.
I was able to get training and prediction working by changing the line to `from tensorflow.python.keras.layers import Dense, InputLayer`. And of course setting `load_outlier_detector` to False.

However, after training, `save_detector(od, filepath)` gives me the following error:

```
  File "E:\venv\lib\site-packages\alibi_detect\utils\saving.py", line 152, in save_detector
    save_tf_vae(detector, filepath)
  File "E:\venv\lib\site-packages\alibi_detect\utils\saving.py", line 739, in save_tf_vae
    detector.vae.encoder.encoder_net.save(model_dir.joinpath('encoder_net.h5'))
  File "E:\venv\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "E:\venv\lib\site-packages\keras\engine\base_layer.py", line 758, in get_config
    raise NotImplementedError(textwrap.dedent(f"""
NotImplementedError: 
Layer ModuleWrapper has arguments ['self', 'module', 'method_name']
in `__init__` and therefore must override `get_config()`.

Example:
class CustomLayer(keras.layers.Layer):
    def __init__(self, arg1, arg2):
        super().__init__()
        self.arg1 = arg1
        self.arg2 = arg2
    def get_config(self):
        config = super().get_config()
        config.update({
            "arg1": self.arg1,
            "arg2": self.arg2,
        })
        return config


```
After looking at a relevant StackOverflow answer [here](https://stackoverflow.com/a/68658024)
I tried changing the relu and Sequence imports to:
```
from tensorflow.python.keras import Sequential
from tensorflow.python.keras.activations import relu
```
Resulting in an error when initializing the outlier detector:
```
  File "E:\venv\lib\site-packages\alibi_detect\od\vae.py", line 68, in __init__
    raise TypeError('No valid format detected for `vae` (tf.keras.Model) '
TypeError: No valid format detected for `vae` (tf.keras.Model) or `encoder_net` and `decoder_net` (tf.keras.Sequential).
```

## Environment
python: 3.9.12
pip list:
`Package                      Version
---------------------------- -------------------
absl-py                      1.0.0
alibi                        0.6.5
alibi-detect                 0.9.1
astunparse                   1.6.3
attrs                        21.4.0
blis                         0.7.7
cachetools                   5.0.0
catalogue                    2.0.7
certifi                      2021.10.8
charset-normalizer           2.0.12
click                        8.0.4
cloudpickle                  2.0.0
colorama                     0.4.4
cycler                       0.11.0
cymem                        2.0.6
decorator                    5.1.1
dill                         0.3.4
dm-tree                      0.1.7
filelock                     3.6.0
flatbuffers                  2.0
fonttools                    4.33.1
gast                         0.5.3
google-auth                  2.6.6
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.44.0
h5py                         3.6.0
huggingface-hub              0.5.1
idna                         3.3
imageio                      2.17.0
importlib-metadata           4.11.3
Jinja2                       3.1.1
joblib                       1.1.0
keras                        2.8.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.2
langcodes                    3.3.0
libclang                     13.0.0
llvmlite                     0.38.0
Markdown                     3.3.6
MarkupSafe                   2.1.1
matplotlib                   3.5.1
murmurhash                   1.0.6
networkx                     2.8
numba                        0.55.1
numpy                        1.21.6
oauthlib                     3.2.0
opencv-python                4.5.5.64
opt-einsum                   3.3.0
packaging                    21.3
pandas                       1.4.2
pathy                        0.6.1
Pillow                       9.1.0
pip                          22.0.4
preshed                      3.0.6
protobuf                     3.20.1
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pydantic                     1.8.2
pyparsing                    3.0.8
python-dateutil              2.8.2
pytz                         2022.1
PyWavelets                   1.3.0
PyYAML                       6.0
regex                        2022.3.15
requests                     2.27.1
requests-oauthlib            1.3.1
rsa                          4.8
sacremoses                   0.0.49
scikit-image                 0.19.2
scikit-learn                 1.0.2
scipy                        1.8.0
seaborn                      0.11.2
setuptools                   61.0.0
six                          1.16.0
smart-open                   5.2.1
spacy                        3.2.4
spacy-legacy                 3.0.9
spacy-loggers                1.0.2
spacy-lookups-data           1.0.3
srsly                        2.4.3
tensorboard                  2.8.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.8.0
tensorflow-io-gcs-filesystem 0.25.0
tensorflow-probability       0.12.2
termcolor                    1.1.0
tf-estimator-nightly         2.8.0.dev2021122109
thinc                        8.0.15
threadpoolctl                3.1.0
tifffile                     2022.4.8
tokenizers                   0.12.1
tqdm                         4.64.0
transformers                 4.18.0
typer                        0.4.1
typing_extensions            4.2.0
urllib3                      1.26.9
wasabi                       0.9.1
Werkzeug                     2.1.1
wheel                        0.37.1
wrapt                        1.14.0
zipp                         3.8.0`

**Comment by jklaise** [comment]
The Pycharm warning is most likely irrelevant as `tensorflow.keras` is absolutely a pakcage and afaik there have been no plans to deprecate the namespace (even the Keras repo uses `from tensorflow.keras import ...`: https://keras.io/). Can you revert the imports to `tensorflow.keras` and check again?

**Comment by aaronrmm** [comment]
Yup, that worked! Thanks! Now to figure out why pycharm is giving me erroneous errors
