### ISSUE TITLE
How to serialize a trained MMDDriftOnline instance and persist it in disk

### ISSUE THREAD

**Issue by eduardorochasoares** [SeldonIO/alibi-detect#525]
Hello, I am trying to serialize a trained instance of the MMDDriftOnline and saving it in the disk, but it seems that the save_model method available does not support this class. I'd like to know if there is a way to do this that I am missing.

Thanks a lot!

**Comment by ascillitoe** [comment]
Hi @eduardorochasoares. You're correct, the `save_detector` function does not current support the `MMDDriftOnline` detector. All drift detectors (excluding those with PyTorch backends/models) will be supported by `save_detector` in the upcoming `v0.10.0` release. If you'd like to try this out prior to the official release, you can access the pre-release version:

https://pypi.org/project/alibi-detect/0.10.0rc1/

In the documentation for v0.10.0 (currently available [here](https://seldon--526.org.readthedocs.build/projects/alibi-detect/en/526/overview/saving.html)) there is a table summarising the save/load support for the various detectors.
