### ISSUE TITLE
Add image dataset example AEGMM and VAEGMM?

### ISSUE THREAD

**Issue by aytek03** [SeldonIO/alibi-detect#536]
Hi sir,

I work with AEGMM and VAEGMM with image dataset. Your example dataset is kddcup and their size is 2D. My image dataset is 4D (1600 * 128 * 128 * 3) and I reshape like this =

1600 * 128 * 128 = 4915200 and 3 so I got 2D array (4915200 , 3).

However, in predict threshold section, I got an error.

It works with perc_outlier=0 (no outlier) but when I change this (let say perc_outlier=5) I got an error:

ValueError: a must be greater than 0 unless no samples are taken.

Therefore, Could you show us to image dataset example in AEGMM and VAEGMM?

Thanks.

**Comment by ascillitoe** [comment]
@ojcobb @arnaudvl @RobertSamoilescu any thoughts on this one?

**Comment by RobertSamoilescu** [comment]
@aytek03, from what you are describing above, it seems that you are not reshaping properly the inputs. The correct reshaping for your use case would be (1600, 128, 128, 3) -> (1600, 128 * 128 * 3). Note that the first dimension is an "indexing" over images and the second would correspond to the flatten representation of an image. 

Another approach to solve your issue might be to use an encoder/decoder with Conv2D/Conv2DTranspose.

Although this suggestions above might solve your technical issues, it might not be that trivial to get the method work, especially for such high input dimensions. There are some theoretical and technical limitation of the method and its implementation that can make it difficult to make it work out of the box.

It would be great if you can provide some details on your use case as we can suggest and confirm that other alternatives available in alibi-detect, such as [AE OD](https://docs.seldon.io/projects/alibi-detect/en/stable/examples/od_ae_cifar10.html) or [VAE OD](https://docs.seldon.io/projects/alibi-detect/en/stable/examples/od_vae_cifar10.html), are suited for your problem. It would be interesting if you can share with us how the dataset looks like and how you would define an outlier.

Thanks!

**Comment by ascillitoe** [comment]
Closing for now. Please feel free to open if any follow-up questions!

**Comment by aytek03** [comment]
Thank you @RobertSamoilescu and @ascillitoe. I missed that point. (reshaping)

If I have enough time, I can start to try this model.

Best regards,
