### ISSUE TITLE
Learned Kernel Detector with Text Data - Example

### ISSUE THREAD

**Issue by akshitasingh0706** [SeldonIO/alibi-detect#559]
Hello, I am trying to implement a Learned Kernel Detector with a text dataset and none of my projections are working. I keep running into errors each time. Would it be possible to share an example of how we can construct neural network projections/kernels for text datasets? Thank you so much!

**Comment by Srceh** [comment]
Hi @akshitasingh0706, thanks for bringing this up.

As projections for text datasets could vary a lot depending on the data structure and pre-processing, we don't have a specific text dataset example at the moment.

I wonder if you can provide more info on your codes/datasets/errors? We can see if there is any quick solution to your problem.
