### ISSUE TITLE
fetch_detector function giving error

### ISSUE THREAD

**Issue by santoshk17** [SeldonIO/alibi-detect#585]
Timed out while searching for meta.dill or meta.pickle files at https://storage.googleapis.com/seldon-models/alibi-detect/od/OutlierVAE/custom.

getting this error while loading pretrained model.

**Comment by mauicv** [comment]
Hey @santoshk17,
Thanks for opening the question. Can I ask what the exact `fetch_detector` call is your running? It looks like your passing `dataset='custom'` to the fetch function but the options are: `adult` or `cifar10`, `kddcup`. The `fetch_detector` loads models trained on specific datasets and isn't really intended to be used outside of the Alibi-Detect [examples](https://docs.seldon.io/projects/alibi-detect/en/stable/examples/od_vae_cifar10.html?highlight=fetch_detector#Load-or-define-outlier-detector).

**Comment by ascillitoe** [comment]
Closing for now. Please feel free to reopen if you have any follow-up problems or questions!
