### ISSUE TITLE
PyTorch `MMDDrift` kernel not being sent to device

### ISSUE THREAD

**Issue by ascillitoe** [SeldonIO/alibi-detect#586]
The `MMDDriftTorch` detector's `kernel` attribute is not sent to the correct device. See [this comment](https://github.com/SeldonIO/alibi-detect/pull/548/files#r932248535).

The following:
```python
self.kernel = kernel(sigma) if kernel == GaussianRBF else kernel
```

should be changed to:
```python
self.kernel = kernel(sigma).to(self.device) if kernel == GaussianRBF else kernel
```

**Comment by ascillitoe** [comment]
@jklaise do you think we should release a patch for this?

**Comment by jklaise** [comment]
@ascillitoe probably since the next release would be at least a few weeks away. I was assuming it's a genuine bug, but weird that not spotted before @arnaudvl

**Comment by arnaudvl** [comment]
Yes definitely a genuine bug, was very surprised when I ran into it during the KeOps PR. Worthy of a patch release I think.

**Comment by ascillitoe** [comment]
OK I shall do this today 👍🏻 

Also agree its weird that we didn't spot it earlier. I assume the kernel was being implicity copied over to device when called or something? Maybe we'll see a speedup now!
