### ISSUE TITLE
 pip install alibi-detect[tensorflow] : no matches found

### ISSUE THREAD

**Issue by lakshyakh93** [SeldonIO/alibi-detect#617]
How to install tensorflow backend

**Comment by ascillitoe** [comment]
Hi @lakshyakh93, `pip install alibi-detect[tensorflow]` is the correct command. There are number of possibilities I can think of that might have caused the "no matches found" error:

- I suspect PyPI itself might have gone down for a short period last night (our own CI temporarily failed). It might be worth just trying the command again today.
- You could be using a very old version of `pip` that does not support the `extras` functionality. What does `pip --version` shoe?
- Are you using zsh by any chance? I have seen issues with correctly interpreting the square brackets on there before.

**Comment by ascillitoe** [comment]
Looks like you closed as I commented! Does that mean it started working again for you?

**Comment by lakshyakh93** [comment]
Hey @ascillitoe , Yes I am using zsh, was missing quote around package name. pip install 'alibi-detect[tensorflow]' worked for me !! Thank you !

**Comment by ascillitoe** [comment]
Ah great, glad to hear you got it working. Thanks for confirming 🙂
