### ISSUE TITLE
Drifted Tabular Data Generation

### ISSUE THREAD

**Issue by LifeBoey** [SeldonIO/alibi-detect#629]
Hi there,

I've been exploring data drift detection and have been wanting to test how good alibi is at determining how much a given dataset has drifted. However, my main concern right now is wondering how to generate drifted data in the first place, and how much to skew them, so that I can get alibi to detect how much drift was applied to them.

So let's say I have a tabular dataframe like this, where I want to drift just the feature of Age.

![adult df](https://user-images.githubusercontent.com/61004414/191708948-f89bd6a0-c0a0-4faf-8bc4-5f9a5de464b4.PNG)

**What are the types of ways to artificially create a drifted dataset from a given dataset?** 

What I've been doing is splitting it into 2 extreme ranges (e.g. one set of <50 Age and one set of >=50 Age), and then mixing the two datasets more and more to create "less" drift. But supposedly for tabular data would something simpler do the trick, such as applying a uniform difference to all the Ages of one dataset work? Applying a random noise to all of the Ages, the noise following some normal distribution? What other standard techniques could be used to apply drift in this manner, and of a degree that can be varied?

Thank you!

**Comment by ascillitoe** [comment]
Hi @LifeBoey, sorry for the delay in getting back to you. Your question is a good one as tabular data is often one of the trickiest to induce drift on (for image data you could just use our in-built [perturbation](https://docs.seldon.io/projects/alibi-detect/en/stable/api/alibi_detect.utils.perturbation.html) module). Both of your suggestions are good solutions, I tend to do the former, i.e. splitting the dataset by a relevant feature value, either with a categorical (i.e. we use `Education` in the Adult/income dataset [here](https://docs.seldon.io/projects/alibi-detect/en/stable/examples/cd_clf_adult.html#Load-Adult-Census-Dataset)) or numerical feature. As you allude to, this will tend to be a little to easy to detect drift on, so you can either make sure your in- and out-of-distribution feature values have some overlap (by duplicating categories like we do in the example above), or by overlapping ranges (e.g. one set <55 Age and one set >45 Age), or simply mix the two distinct splits as you suggested. Note that in both cases, it is good practice to apply some extra preprocessing to ensure you don't have instances duplicated between the two sets. Another thing that I tend to do is remove whichever feature you have used for the dataset splitting (e.g. `Age` in your case). If you've picked a sensible feature to subsample on, the rest of your features should exhibit more subtle drift, whereas the drift of the feature you've subsampled on will be quite extreme.

As an alternative, you could also apply perturbations to numerical data, such as various types of noise or offsets. If you want it to be somewhat realistic then what you apply will depend on the specific feature. For categorical features, you could also crudely swap feature values etc. 

Another approach could be something like the [Breeds](https://github.com/MadryLab/BREEDS-Benchmarks) library, however, this will only work if your dataset has a clear class hierachy. Finally, if you want complete control over the type and degree of drift, then you really need to stick to synthetic data. You could start as simple as Gaussian blobs, and go from there. You might also get some ideas from libraries such as [data-streams](https://github.com/alipsgh/data-streams), although you'll need to be careful to consider autocorrelation if considering any of the time-series datasets.
