### ISSUE TITLE
The specific meaning of expected run-time (ERT)

### ISSUE THREAD

**Issue by SeibertronSS** [SeldonIO/alibi-detect#652]
Hello, everyone. I'm very interested in Alibi's online drift detection, but according to the documentation, I don't quite understand how the whole online drift detection works. In particular, I don't understand what exactly expected run-time (ERT) means.

**Comment by ascillitoe** [comment]
Hi @SeibertronSS, please ignore if you've already come across this section of the docs, but the core concepts surrounding online drift detectors are covered in [Online drift detectors](https://docs.seldon.io/projects/alibi-detect/en/stable/cd/background.html#online-drift-detectors), in particular, the section on [Expected run-time and detection delay](https://docs.seldon.io/projects/alibi-detect/en/stable/cd/background.html#expected-run-time-and-detection-delay).

In short, our offline drift detectors expect a batch of test data `x` to be passed to `predict`, and they compare this batch of data to the reference data `x_ref`. Under _no-drift_, when $P(x)= P(x_{ref})$, the offline detectors will return false positives a certain fraction of the time. This fraction is the _false-positive-rate_ (FPR), and if the detector is well calibrated, it should be equal to the p-value threshold given to the detector via the `p_val` argument. Under _drift_, when $P(x) \ne P(x_{ref})$, we expect the detector to return true positives a high fraction of the time. This fraction is the _true-positive-rate_ (TPR), or _test power_.

For online detectors, the situation is slightly different. We pass single instances of test data `x` to `predict`. On each `predict` call we test for drift using the last $W$ samples of test data, where $W$ can be interpreted as the size of the _test window_ (see [Online drift detectors](https://docs.seldon.io/projects/alibi-detect/en/stable/cd/background.html#online-drift-detectors)). The offline concepts of FPR and TPR no longer apply. Instead, when under _no-drift_, we consider the _expected-run-time_ (ERT). This is the number of time-steps (`predict` calls) the detector will run (on average) before returning a false positive. It follows that $ERT = 1/FPR$. When under _drift_, we expect the detector to run (on average) for a certain number of time-steps (the _actual-detection-delay_, ADD) before correctly detecting drift. For an applied demonstration of these concepts, I recommend our [Online Drift Detection on the Wine Quality Dataset](https://docs.seldon.io/projects/alibi-detect/en/stable/examples/cd_online_wine.html) example.

**Comment by SeibertronSS** [comment]
@ascillitoe Thank you very much!
