### ISSUE TITLE
Incorrect probabilities returned by ClassifierDrift 

### ISSUE THREAD

**Issue by arnaudvl** [SeldonIO/alibi-detect#655]
The ClassifierDrift detector incorrectly returns prediction probabilities since it does not take the `train_size` split into training and held out testing data into account. So for instance if `train_size=.5`, then all prediction probabilities will be returned as reference data probabilities:

```python
        return p_val, dist, probs_sort[:n_ref, 1], probs_sort[n_ref:, 1]
```
where `n_ref` equals all reference instances, including those used for training.

**Comment by ascillitoe** [comment]
Will be fixed in v0.10.4. See #662.
