### ISSUE TITLE
OutlierVAE with image_size 512

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [SeldonIO/alibi-detect#659]
Hi
First of all, thanks for your great effort on this repo!

Have you tried to train the OutlierVAE on images with size bigger than 64?
I can't build the layers correctly so i train on image size 512. Any insights how to do it or if its already done?

Any help is appreciated!
Thanks in advance!

**Comment by mauicv** [comment]
Hey @SuroshAhmadZobair, 
Thanks for opening the issue. Perhaps take a look at my answer to this [issue](https://github.com/SeldonIO/alibi-detect/issues/547) specifically I think the architecture defined in this [comment](https://github.com/SeldonIO/alibi-detect/issues/547#issuecomment-1172318285) should work. Let me know if that helps.

**Comment by SuroshAhmadZobair** [comment]
Thanks a lot @mauicv!

It was very informative and straightforward!
