### ISSUE TITLE
Question: Detecting Concept Drift in a Text Datasets

### ISSUE THREAD

**Issue by CMobley7** [SeldonIO/alibi-detect#66]
I was hoping to use Alibi-detect in order to detect concept drift in a text datastream. However, based on the documentation, it doesn't appear that this is possible. If possible, can you suggest any other project(s) that would allow for this functionality or would your library work if I were to tokenize my data first?

**Comment by arnaudvl** [comment]
Hi @CMobley7 , we currently haven't included concept drift algorithms in the library yet. It is however in our near term roadmap. I can't immediately think of other projects but can give some suggestions. 

The first would be quite simple: use a similarity measure between the tokens in your new data coming in and the data you are using for comparison (e.g. the previous stream or some training distribution). To make the measure invariant to the word positioning, you could use for each token in the stream the minimum similarity score over the tokens in the comparison set. The overall measure would then be the mean of the minimum similarity scores over the tokens in the new stream. This way, you could track a simple measure of similarity of your datastream. For the scores, you can use for instance a pretrained spaCy corpus.

Another idea would be to feed your tokens into pretrained embedding layers. Then you could fit multivariate Gaussian distributions to the embedded tokens; one for the comparison tokens and one for the new data coming in. After that, you could compute a distance metric or probability score between those 2 distributions.

In case you are interesting in helping us implement one of these methods, don't hesitate to reach out.

**Comment by arnaudvl** [comment]
#130
