### ISSUE TITLE
Prediction Drift

### ISSUE THREAD

**Issue by SeibertronSS** [SeldonIO/alibi-detect#693]
Hi everyone. I just came into contact with drift detection. I found that drift detection can be divided into input data detection and prediction detection. I wonder if the method in Alibi-Detect can be used for prediction detection.

**Comment by Srceh** [comment]
Hi @SeibertronSS, yes, we have detectors that are designed for model predictions. Please check [here](https://docs.seldon.io/projects/alibi-detect/en/latest/api/alibi_detect.cd.model_uncertainty.html) for examples.

**Comment by SeibertronSS** [comment]
> Hi @SeibertronSS, yes, we have detectors that are designed for model predictions. Please check [here](https://docs.seldon.io/projects/alibi-detect/en/latest/api/alibi_detect.cd.model_uncertainty.html) for examples.

Thanks for your help!
