### ISSUE TITLE
ValueError: Too many repeat instances for LSDD-based detection. Try using MMD-based detection instead

### ISSUE THREAD

**Issue by Sandeep-Bhogaraju-TA** [SeldonIO/alibi-detect#694]
Hi, I am monitoring my data with LSDD Drift detector (single feature drift detection). I have the cd.predict() under a retry logic (using retry package)(retry upto 10 times).

Sometimes I observe that the I get ValueError: Too many repeat instances for LSDD-based detection. Try using MMD-based detection instead.

What can I do to solve this error.

`/databricks/python/lib/python3.9/site-packages/decorator.py in fun(*args, **kw)
    230             if not kwsyntax:
    231                 args, kw = fix(args, kw, sig)
--> 232             return caller(func, *(extras + args), **kw)
    233     fun.__name__ = func.__name__
    234     fun.__doc__ = func.__doc__

/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/retry/api.py in retry_decorator(f, *fargs, **fkwargs)
     71         args = fargs if fargs else list()
     72         kwargs = fkwargs if fkwargs else dict()
---> 73         return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
     74                                 logger)
     75 

/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/retry/api.py in __retry_internal(f, exceptions, tries, delay, max_delay, backoff, jitter, logger)
     31     while _tries:
     32         try:
---> 33             return f()
     34         except exceptions as e:
     35             _tries -= 1

/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/alibi_detect/cd/lsdd.py in predict(self, x, return_p_val, return_distance)
    120         'data' contains the drift prediction and optionally the p-value, threshold and LSDD metric.
    121         """
--> 122         return self._detector.predict(x, return_p_val, return_distance)
    123 
    124     def score(self, x: Union[np.ndarray, list]) -> Tuple[float, float, float]:

/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/alibi_detect/cd/base.py in predict(self, x, return_p_val, return_distance)
    793         """
    794         # compute drift scores
--> 795         p_val, dist, distance_threshold = self.score(x)
    796         drift_pred = int(p_val < self.p_val)
    797 

/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/alibi_detect/cd/tensorflow/lsdd.py in score(self, x)
    152         y_perms = [perm[n_x:] for perm in perms]
    153 
--> 154         lsdd_permuted, _, lsdd = permed_lsdds(  # type: ignore
    155             k_all_c, x_perms, y_perms, self.H, lam_rd_max=self.lambda_rd_max, return_unpermed=True
    156         )

/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/alibi_detect/utils/tensorflow/distance.py in permed_lsdds(k_all_c, x_perms, y_perms, H, H_lam_inv, lam_rd_max, return_unpermed)
    227             else:
    228                 msg = "Unknown error. Try using MMD-based detection instead"
--> 229             raise ValueError(msg)
    230         lambda_index = int(less_than_rd_inds[0])
    231         lam = candidate_lambdas[lambda_index]

ValueError: Too many repeat instances for LSDD-based detection.                 Try using MMD-based detection instead`

**Comment by ojcobb** [comment]
Hi Sandeep,

The LSDD method is designed to detect differences between continuous probability distributions. If your data contains repeat instances then the underlying distribution isn't continuous (in the probabilistic sense) and the LSDD method can sometimes break down.

Therefore for samples containing repeat instances we instead recommend alternative detectors such as `MMDDrift`. If you're set on using `LSDDDrift` you could try perturbing the repeat instances with a very small amount of noise such that they're not quite the same.

**Comment by Sandeep-Bhogaraju-TA** [comment]
Thank you so much, this explains why I get the issue
