### ISSUE TITLE
[Question] Interpreting stat_val for drift detectors

### ISSUE THREAD

**Issue by Sandeep-Bhogaraju-TA** [SeldonIO/alibi-detect#697]
Hi, 
I have a question regarding interpreting stat_val.
For eg. I use Mixed Tabular Detector for a dataset and I get the following output (Removing the feature level values)-

"is_drift": [1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0],
"stat_val": [
    92.14810943603516,
    55.293983459472656,
    0.061000000685453415,
    0.07000000029802322,
    0.06700000166893005,
    0.03700000047683716,
    0.1289999932050705,
    0.08900000154972076,
    0.1379999965429306,
    0.00800000037997961,
    0.01600000075995922,
],
"p_val": [
    8.04263256623271e-22,
    0.0032876001205295324,
    0.04642140120267868,
    0.01416832022368908,
    0.021427907049655914,
    0.4888690412044525,
    1.0296152197497577e-07,
    0.0006770353065803647,
    9.08852548775485e-09,
    1.0,
    0.9993510842323303,
],

From above, it shows many of the features drifted, but the stat_val for these features are bigger for features 1&2 and for others it is small.
Are the stat_vals relative to the features ? 
Can I interpret that Feature 1 & 2 have drifted a lot more than other features as their stat_vals are smaller?
In this case the Feature 1 & 2 are "month" (range 1-12) and "day" (range 1- 31)

**Comment by ojcobb** [comment]
Hi Sandeep,

For the mixed-type tabular drift detector the test statistic used for categorical features differs to that used for numerical features and therefore if comparing the `stat_val`s be sure only to do so between features of the same type. 

The `p_val`s however can be interpreted as a normalised version of the `stat_val`s that can be compared across feature types. In this case you can see that the first feature has the lowest p-value and has therefore drifted the most, however the second feature actually hasn't drifted as heavily as some of the later features.

Hope that helps.

**Comment by Sandeep-Bhogaraju-TA** [comment]
Thank you Oliver, this answers my question.
