### ISSUE TITLE
Algorithm Contribution

### ISSUE THREAD

**Issue by gjy688** [SeldonIO/alibi-detect#704]
Hello,

We designed a new drift detection algorithm SDDM(SHAP Value-Based Unsupervised Drift Detection Method), you can see it on [https://github.com/hope-coder/SDDM]().We compared with other drift detection algorithms on some benchmark artificial datasets and real-world datasets, and SDDM have a advantage on every indicractor. 

We want to integrate SDDM into the cd module of alibi-detect, Would you be interested in this? We have integrated SDDM into the alibi-detect on local.But the code still falls short of the contribution requirements in terms of standardization. If you agree to this proposal，we will continue do with this and contribute our algorithm.

**Comment by ojcobb** [comment]
Hi gjy688 :wave: 

Thank you for your interest in contributing what sounds like an interesting algorithm!

However having looked through your repo I haven't managed to find any description of the algorithm and its associated motivation etc. I assume these are contained in the paper you reference but I can't find that online. Perhaps you would like to share it with us? We could then determine whether it meets various desiderata we consider when evaluating which detectors to include in our library. :slightly_smiling_face:

**Comment by ascillitoe** [comment]
Hi @gjy688, I am closing this for now, but feel free to reopen if you wish to continue the conversation.
