### ISSUE TITLE
Intermittent `IndexError` in `MMDDriftOnlineTF` with older Python (and tensorflow?) versions

### ISSUE THREAD

**Issue by ascillitoe** [SeldonIO/alibi-detect#706]
## Problem

A not-seen-before error is occurring during CI [here](https://github.com/SeldonIO/alibi-detect/actions/runs/3883607868/jobs/6625111418), in the `test_save_multivariate_online_state` test function. The error is:

```
IndexError: too many indices for array: array is 2-dimensional, but 31 were indexed
```

It occurs in `MMDDriftOnlineTF._update_state()` at the line:

```python
kernel_col = self.kernel(self.x_ref[self.ref_inds], x_t)
```

For context, `self.x_ref` is `np.ndarray: (50,4)` and `self.ref_inds` is `tf.EagerTensor: (31,)`. Strangely, this error doesn't occur in the `test_save_onlinemmddrift` test function where  `self.x_ref` is `np.ndarray: (50,2)` and `self.ref_inds` is `tf.EagerTensor: (41,)`.

## Possible cause
The error only occurs in the Python 3.7 build but not the 3.10 build. The `tensorflow` version is the same in both (2.10.1), but the Python 3.7 build uses an older `numpy` version (`1.21.6` compared to `1.23.5` in 3.10 build). I suspect the error might be an obscure compatibly error between the old-ish `numpy` version and new-ish `tensorflow` version. The `self.x_ref[self.ref_inds]` operation involves indexing a ndarray (`self.x_ref`) with a tf Tensor (`self.ref_inds`). Supporting evidence is the fact that `self.x_ref[self.ref_inds.numpy()]` fixes the issue.

## Possible solutions

We could change the problematic line to `self.x_ref[self.ref_inds.numpy()]`, or alternatively `self.x_ref[self.ref_inds, :]` appears to fix things (I think this is fine since we always expect `x_ref` and `x` to have shape (`n_instances`, `n_features`), even when `n_features=1`.

**Comment by ascillitoe** [comment]
@ojcobb, @mauicv could I get your thoughts on this please? Very strange!

**Comment by mauicv** [comment]
Just putting [this](https://colab.research.google.com/drive/1k_IDlrB4NP09aRcPNYBh2zs3uVcw_ClT?usp=sharing) here for easy recreation of the error

**Comment by jklaise** [comment]
My gut feels tells me that indexing a `numpy` array with a `tensorflow` tensor sounds like bad news and it's only coincidental that it worked in some cases, should we just be more careful and not mix types like this?

**Comment by ascillitoe** [comment]
Yeh agreed 👍🏻
