### ISSUE TITLE
Vanilla AE outlier detector

### ISSUE THREAD

**Issue by mishinma** [SeldonIO/alibi-detect#74]
Hi, 

Is there a reason why there is no vanilla AE outlier detector in `od` module? This would be nice to have as a baseline.

**Comment by jklaise** [comment]
Good question! I'll defer to @arnaudvl to answer this.

**Comment by arnaudvl** [comment]
Hi @mishinma , the main reason is that I found VAE to outperform AE pretty consistently in my experience, so it was prioritised. It would indeed be straightforward to add a vanilla AE outlier detector as a baseline. The autoencoder components are already [here](https://github.com/SeldonIO/alibi-detect/blob/master/alibi_detect/models/autoencoder.py) and the AE detector would be quite similar to the VAE one as implemented [here](https://github.com/SeldonIO/alibi-detect/blob/master/alibi_detect/od/vae.py) but without the samples option. Would you be keen to implement it by any chance? If not, we'll implement it when some time frees up.

**Comment by mishinma** [comment]
Hi @arnaudvl, that makes sense. I've actually already implemented it in my fork. I created an example notebook, but need to add tests. Please review when you have time. Thanks

**Comment by arnaudvl** [comment]
Will definitely do! Thanks a lot

**Comment by arnaudvl** [comment]
#86
