### ISSUE TITLE
Issue regarding MMDDrift

### ISSUE THREAD

**Issue by righelcpm** [SeldonIO/alibi-detect#741]
I am trying to run this:

sea_noise = pd.read_csv("sea_0123_gradual_noise_0.2_1000.csv")
X_ref = np.transpose(np.vstack([sea_noise.X2.values, sea_noise.X1.values]))
from alibi_detect.cd import MMDDrift
cd = MMDDrift(X_ref, backend='tensorflow', p_val=.05)
preds = cd.predict(sea_noise.X1)

[sea_0123_gradual_noise_0.2_1000.csv](https://github.com/SeldonIO/alibi-detect/files/10706045/sea_0123_gradual_noise_0.2_1000.csv)

____________________________________________________________________________________

The message I get:

InvalidArgumentError Traceback (most recent call last)
in
----> 1 preds = cd.predict(sea_noise.X1)

6 frames
[/usr/local/lib/python3.8/dist-packages/alibi_detect/utils/tensorflow/distance.py](https://localhost:8080/#) in squared_pairwise_distance(x, y, a_min, a_max)
28 x2 = tf.reduce_sum(x ** 2, axis=-1, keepdims=True)
29 y2 = tf.reduce_sum(y ** 2, axis=-1, keepdims=True)
---> 30 dist = x2 + tf.transpose(y2, (1, 0)) - 2. * x @ tf.transpose(y, (1, 0))
31 return tf.clip_by_value(dist, a_min, a_max)
32

InvalidArgumentError: Exception encountered when calling layer "gaussian_rbf" (type GaussianRBF).

Matrix size-incompatible: In[0]: [999,2], In[1]: [1,999] [Op:MatMul]

Call arguments received by layer "gaussian_rbf" (type GaussianRBF):
• x=tf.Tensor(shape=(999, 2), dtype=float32)
• y=0 0.174903
1 1.123120
2 4.601012
3 1.871278
4 6.550663
...
994 6.276959
995 2.788704
996 1.803116
997 4.313775
998 6.234055
Name: X1, Length: 999, dtype: float64
• infer_sigma=False

**Comment by ascillitoe** [comment]
Hi @righelcpm. The detector's TensorFlow backend is returning `Matrix size-incompatible: In[0]: [999,2], In[1]: [1,999] [Op:MatMul]` because your reference data `X_ref` has dimensions `(999, 2)`, whereas your "test" data passed to `predict` has dimensions `(999, 1)`. Both data sets should have the same features.

If I change your code to:

```python
import pandas as pd
import numpy as np
from alibi_detect.cd import MMDDrift

sea_noise = pd.read_csv("sea_0123_gradual_noise_0.2_1000.csv")
X_ref = np.transpose(np.vstack([sea_noise.X2.values, sea_noise.X1.values]))
X_test = np.transpose(np.vstack([sea_noise.X2.values, sea_noise.X1.values]))

cd = MMDDrift(X_ref, backend='tensorflow', p_val=.05)
preds = cd.predict(X_test)
print(preds)
```

This returns:

```
{'data': {'is_drift': 0, 'distance': -0.0011618137, 'p_val': 1.0, 'threshold': 0.05, 'distance_threshold': 0.0017448664}, 'meta': {'name': 'MMDDriftTF', 'online': False, 'data_type': None, 'version': '0.12.0dev', 'detector_type': 'drift', 'backend': 'tensorflow'}}
```

No drift is detected in this case because `X_test` is drawn from the same distribution as the reference data `X_ref` (in fact they are the same instances).

**Comment by ascillitoe** [comment]
Hi @righelcpm I am closing this for now, but please feel free to reopen if you have any issues with the above.
