### ISSUE TITLE
Argument's size is not matched to multiply matrix in MMDDriftOnline function. And I have some questions about this function.

### ISSUE THREAD

**Issue by KevinRyu** [SeldonIO/alibi-detect#786]
Hi, 

I am trying to use MMDDriftOnline function for my task. 
By the way, I got an error like the following while running the detection code.
I have some questions about error itself and related to this.

1. What do you think is the root cause for this error? 
    I set the sizes and dimensions of X_ref and X_h0 to same. But the shape is mismatched.
   "In[0] mismatch In[1] shape: 1 vs. 8000: [7961,1] [8000,1] 0 0 [Op:MatMul]"

2. Can I set the sigma to float or numpy array? What do you think the range of this value?
   I want to use this parameter to adjust sensitivity of detection.

3. Does ERT and window size affect this error? Is there a formula needed to set these values? I saw that n_bootstraps should be set to a size of 1 order or more of ERT How is it appropriate to set it?

4. Do you have information on how to calculate the threshold and the formula? In what order or method do you calculate the threshold?
```python
# Initialize detector
# Set detector
ert = 50 
window_size = 20

X_ref = reference_set['value'].to_numpy().reshape(-1, 1)

print(X_ref.shape)

cd = MMDDriftOnline(
    X_ref, 
    ert, 
    window_size, 
    backend='tensorflow', 
    sigma=1.5, 
    preprocess_fn=None, 
    n_bootstraps=500, 
    verbose=True
)

# result
(8000, 1)
Generating permutations of kernel matrix..
100%|██████████| 500/500 [00:00<00:00, 885.68it/s]
Computing thresholds: 100%|██████████| 20/20 [00:14<00:00,  1.38it/s]

# predict
X_h0 = test_set['value'].sample(n=8000).to_numpy().reshape(-1, 1)
print(X_h0.shape)

pred = cd.predict(X_h0, return_test_stat=True)

print(pred['data']['is_drift'])

# output and error messages
(8000, 1)

InvalidArgumentError                      Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_23108\1849088644.py in <cell line: 4>()
      2 print(X_h0.shape)
      3 
----> 4 pred = cd.predict(X_h0, return_test_stat=True)
      5 
      6 print(pred['data']['is_drift'])

c:\Users\user\envs\alibidet\lib\site-packages\alibi_detect\cd\mmd_online.py in predict(self, x_t, return_test_stat)
    138         'data' contains the drift prediction and optionally the test-statistic and threshold.
    139         """
--> 140         return self._detector.predict(x_t, return_test_stat)
    141 
    142     def score(self, x_t: Union[np.ndarray, Any]) -> float:

c:\Users\user\envs\alibidet\lib\site-packages\alibi_detect\cd\base_online.py in predict(self, x_t, return_test_stat)
    190         """
    191         # Compute test stat and check for drift
--> 192         test_stat = self.score(x_t)
    193         threshold = self.get_threshold(self.t)
    194         drift_pred = int(test_stat > threshold)

c:\Users\user\envs\alibidet\lib\site-packages\alibi_detect\cd\tensorflow\mmd_online.py in score(self, x_t)
    211         """
    212         x_t = super()._preprocess_xt(x_t)
--> 213         self._update_state(x_t)
    214         k_yy = self.kernel(self.test_window, self.test_window)
    215         mmd = (

c:\Users\user\envs\alibidet\lib\site-packages\alibi_detect\cd\tensorflow\mmd_online.py in _update_state(self, x_t)
    193         """
    194         self.t += 1
--> 195         kernel_col = self.kernel(tf.gather(self.x_ref, self.ref_inds), x_t)
    196         self.test_window = tf.concat([self.test_window[(1 - self.window_size):], x_t], axis=0)
    197         self.k_xy = tf.concat([self.k_xy[:, (1 - self.window_size):], kernel_col], axis=1)

c:\Users\user\envs\alibidet\lib\site-packages\keras\engine\base_layer.py in __call__(self, *args, **kwargs)
   1035         with autocast_variable.enable_auto_cast_variables(
   1036             self._compute_dtype_object):
-> 1037           outputs = call_fn(inputs, *args, **kwargs)
   1038 
   1039         if self._activity_regularizer:

c:\Users\user\envs\alibidet\lib\site-packages\alibi_detect\utils\tensorflow\kernels.py in call(self, x, y, infer_sigma)
     76         y = tf.cast(y, x.dtype)
     77         x, y = tf.reshape(x, (x.shape[0], -1)), tf.reshape(y, (y.shape[0], -1))  # flatten
---> 78         dist = distance.squared_pairwise_distance(x, y)  # [Nx, Ny]
     79 
     80         if infer_sigma or self.init_required:

c:\Users\user\envs\alibidet\lib\site-packages\alibi_detect\utils\tensorflow\distance.py in squared_pairwise_distance(x, y, a_min, a_max)
     28     x2 = tf.reduce_sum(x ** 2, axis=-1, keepdims=True)
     29     y2 = tf.reduce_sum(y ** 2, axis=-1, keepdims=True)
---> 30     dist = x2 + tf.transpose(y2, (1, 0)) - 2. * x @ tf.transpose(y, (1, 0))
     31     return tf.clip_by_value(dist, a_min, a_max)
     32 

c:\Users\user\envs\alibidet\lib\site-packages\tensorflow\python\ops\math_ops.py in binary_op_wrapper(x, y)
   1365         #   r_binary_op_wrapper use different force_same_dtype values.
   1366         x, y = maybe_promote_tensors(x, y, force_same_dtype=False)
-> 1367         return func(x, y, name=name)
   1368       except (TypeError, ValueError) as e:
   1369         # Even if dispatching the op failed, the RHS may be a tensor aware

c:\Users\user\envs\alibidet\lib\site-packages\tensorflow\python\ops\math_ops.py in matmul_wrapper(a, b, name)
   3761   if ops._numpy_style_type_promotion:
   3762     return a._matmul(b)
-> 3763   return matmul(a, b, name=name)
   3764 matmul_wrapper.__doc__ = matmul.__doc__
   3765 _OverrideBinaryOperatorHelper(matmul_wrapper, "matmul")

c:\Users\user\envs\alibidet\lib\site-packages\tensorflow\python\util\dispatch.py in wrapper(*args, **kwargs)
    204     """Call target, and fall back on dispatchers if there is a TypeError."""
    205     try:
--> 206       return target(*args, **kwargs)
    207     except (TypeError, ValueError):
    208       # Note: convert_to_eager_tensor currently raises a ValueError, not a

c:\Users\user\envs\alibidet\lib\site-packages\tensorflow\python\ops\math_ops.py in matmul(a, b, transpose_a, transpose_b, adjoint_a, adjoint_b, a_is_sparse, b_is_sparse, output_type, name)
   3652             a, b, adj_x=adjoint_a, adj_y=adjoint_b, Tout=output_type, name=name)
   3653       else:
-> 3654         return gen_math_ops.mat_mul(
   3655             a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
   3656 

c:\Users\user\envs\alibidet\lib\site-packages\tensorflow\python\ops\gen_math_ops.py in mat_mul(a, b, transpose_a, transpose_b, name)
   5693       return _result
   5694     except _core._NotOkStatusException as e:
-> 5695       _ops.raise_from_not_ok_status(e, name)
   5696     except _core._FallbackException:
   5697       pass

c:\Users\user\envs\alibidet\lib\site-packages\tensorflow\python\framework\ops.py in raise_from_not_ok_status(e, name)
   6939   message = e.message + (" name: " + name if name is not None else "")
   6940   # pylint: disable=protected-access
-> 6941   six.raise_from(core._status_to_exception(e.code, message), None)
   6942   # pylint: enable=protected-access
   6943 
```
c:\Users\user\envs\alibidet\lib\site-packages\six.py in raise_from(value, from_value)

InvalidArgumentError: In[0] mismatch In[1] shape: 1 vs. 8000: [7961,1] [8000,1] 0 0 [Op:MatMul]

First of all, thank you for your support.

**Comment by jklaise** [comment]
Hi @KevinRyu, it would be very helpful if you could format your code snippets and output using Github markdown syntax, otherwise it's very hard to read, see here: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by KevinRyu** [comment]
> Hi @KevinRyu, it would be very helpful if you could format your code snippets and output using Github markdown syntax, otherwise it's very hard to read, see here: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

Thanks for your inform. I edited some markdown symtax. Let me know If this issues still have some problems.

**Comment by ascillitoe** [comment]
Hi @KevinRyu, thank you for reformatting the issue.

It looks like you are calling `predict` on the entirety of your `(8000,1`) test data array `X_h0` at once, is that the case? Since `MMDDriftOnline` is an [online detector](https://docs.seldon.io/projects/alibi-detect/en/stable/cd/background.html#online-drift-detectors), it should be called on single instances at a time i.e. on arrays of shape `(1,`) in your case.

For a complete example:

```python
import numpy as np
from alibi_detect.cd import MMDDriftOnline

# Create reference data and init detector
X_ref = np.random.normal(loc=0, scale=1, size=(800, 1))
dd = MMDDriftOnline(X_ref, ert=200, window_size=40)

# Test no-drift case (measure actual run time)
X_h0 = np.random.normal(loc=0, scale=1, size=(800, 1))

dd.reset_state()
t = 0
for X_t in X_h0:
  pred = dd.predict(X_t)
  if pred['data']['is_drift'] == 1:
    break
  else:
    t += 1
ART = t

# Test drift case  (measure actual detection delay)
X_h1 = np.random.normal(loc=0.5, scale=1, size=(800, 1))

dd.reset_state()
t = 0
for X_t in X_h1:
  pred = dd.predict(X_t)
  if pred['data']['is_drift'] == 1:
    break
  else:
    t += 1
ADD = t

# Print results
print('ART: %s' % ART)
print('ADD: %s' % ADD)

```

Regarding your question about expected run time (ERT), this is the number of time-steps we expect the detector to run for in the absence of drift. In other words, it is the inverse of the false positive rate (FPR). Choosing a larger ERT value will mean less false positives, however the detector will be less sensitive to slight drift. As for the window size, smaller windows allow a faster response to severe drift, whilst larger windows allow more power to detect slight drift. The exact choice of `ert` and `window_size` depends on your use case, and which of the above characteristics is more important to you. For more resources regarding this, I recommend the [MMDDriftOnline docs](https://docs.seldon.io/projects/alibi-detect/en/stable/cd/methods/onlinemmddrift.html#Online-Maximum-Mean-Discrepancy), the [intro to online detectors](https://docs.seldon.io/projects/alibi-detect/en/stable/cd/background.html#online-drift-detectors), and [this video](https://www.youtube.com/watch?v=JaPMFf0cKlM). 

Note that in the example above, I measure the actual run time (ART) in the no-drift case, ideally ART should be approximately equal to your chosen ERT. I also measure the actual detection delay (ADD) in the drifted case, ideally this will be as small as possible, since you want to detect drift as soon as possible. Note however, that ART will only equal ERT **on average**. You will need to measure ART and ADD over a large number of different randomised `X_ref`, `X_h0`, and `X_h1` sets, and take the averaged value for it to be equal to `ERT`. This is what we do in the [Online Drift Detection on the Wine Quality Dataset](https://docs.seldon.io/projects/alibi-detect/en/stable/examples/cd_online_wine.html) example (check out the "Q-Q plots").

**Comment by ascillitoe** [comment]
Closing for now but please reopen if you encounter further issues.
