### ISSUE TITLE
`prophet` breaking on `holidays=0.25`

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/alibi-detect#790]
See here: https://github.com/facebook/prophet/issues/2430

A short-term solution would be to pin `holidays<0.25` to fix CI, but a patch release would be required to enable `OutlierProphet` working on fresh installs without user intervention. I would suggest pinning on CI and keeping this issue open, perhaps upstream will update soon.

- [ ] Pin `holidays<0.25`
- [ ] Patch release

**Comment by jklaise** [comment]
Closing as upstream has released a patch (re-running tests now) - https://github.com/facebook/prophet/releases/tag/v1.1.3

**Comment by jklaise** [comment]
Reopening (briefly) as 1.1.3 hasn't been published on PyPI.

**Comment by ascillitoe** [comment]
@jklaise looks like its published now :)

**Comment by jklaise** [comment]
Indeed and the nightly CI finished successfully.
