### ISSUE TITLE
`typing-extensions` 4.6.0 breakage

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/alibi-detect#796]
- https://github.com/python/typing_extensions/issues/179
- https://github.com/python/typing_extensions/issues/181
- https://github.com/pydantic/pydantic/issues/5821

User workaround until it's fixed: `pip install typing-extensions==4.5.0`.

**Comment by jklaise** [comment]
Fixed upstream.

**Comment by ascillitoe** [comment]
@jklaise looks like pydantic [v.1.10.8](https://github.com/pydantic/pydantic/releases/tag/v1.10.8) fixes this so we can close?

**Comment by ascillitoe** [comment]
Beat me to it...
