### ISSUE TITLE
Return data from od fit methods

### ISSUE THREAD

**Issue by mauicv** [SeldonIO/alibi-detect#813]
- [x] Currently when you can fit on `gmm` and `svm` detectors the user can specify verbosity, however, we don't return any logs of the fit process despite computing them internally, These should be returned.
- [x] Also, make sure that returned data is consistent.

**Comment by jklaise** [comment]
Do you mean actually return some object with the logs or just fiddling with the `logging` levels?

Bigger than this issue, but it's a great point to consider how we could expose application level logging. From our point of view, we just need to sprinkle `logging` statements, but then it's up to the user/application to define where to log and which level to expose (as in, our `verbose`) flags would not affect these. Good to check with `scikit-learn` as they have `verbose` flags too.

**Comment by mauicv** [comment]
I mean some object with the logs although perhaps logging would be better. Specifically in the case of `gmm` we allow a convergence threshold to be set. The training ends on the basis of this criterion being met or the training process running for `max_epochs`. I felt this should be returned to the user so they can check if this has occured or at least set this value on the detector somewhere.

**Comment by jklaise** [comment]
OK I see, it makes sense to both return something that can be programatically checked and also logging progress, both of which are kind of orthogonal.
