### ISSUE TITLE
Error related to 'scale_identity_multiplier' in tensorflow

### ISSUE THREAD

**Issue by nys3015** [SeldonIO/alibi-detect#820]
I found 'TypeError: MultivariateNormalDiag.An error such as __init__() got an unexpected keyword argument 'scale_identity_multiplier' .
These errors are found in the 38th line of (alibi_detect/models/tensorflow/losses.py ).

Referring to the document in 'tensorflow' (https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/MultivariateNormalDiag) , we found that the 'multivariatenormalDiag' in tensorflow no longer uses scale_identity_multiplier.

In this regard, it seems that a quick correction is needed.

**Comment by ascillitoe** [comment]
Hi @nys3015, thank you for raising this. We will work on a fix.

**Comment by ascillitoe** [comment]
Note to team: 

Looks like `scale_identify_multiplier` was removed from `tensorflow-probability` in [this commit](https://github.com/tensorflow/probability/commit/ca8485023767fc021e277ca1a987449d90f21cea), and released in `v0.20.0`.

**Comment by ascillitoe** [comment]
Hi @nys3015, thanks for raising this. I just realised we've actually seen this issue in our tests already (See [comment](https://github.com/SeldonIO/alibi-detect/pull/785#issuecomment-1558873806)), but only in `tensorflow-probability v0.20.0`, which we don't officially support yet. 

Are you using `tensorflow-probability v0.20.0` by any chance? If so, are you able to downgrade to `v0.19`? As a side-note, could I check how you installed tensorflow please? If you installed it via `pip install alibi-detect[tensorflow]` I would have thought pip would ensure only compatible versions are installed.
