### ISSUE TITLE
Error when installing holidays 

### ISSUE THREAD

**Issue by robinicole** [SeldonIO/alibi-detect#92]
The holiday package (dependence of fbprophe) returns an error (https://github.com/dr-prodigy/python-holidays/issues/277). I fixed the issue by pinning the holiday package to version 0.9.11  (`pip install --upgrade holidays==0.9.11`)

**Comment by jklaise** [comment]
Well spotted, `fbprophet` should release a new version soon so we can pin that instead as holidays is an indirect dependency.

**Comment by arnaudvl** [comment]
Temporarily fixed by pinning the holidays version in #94
