### ISSUE TITLE
pip install alibi-detect issue

### ISSUE THREAD

**Issue by czkn** [SeldonIO/alibi-detect#93]
when I install alibi-detect，it turns out：
```
ERROR: Could not find a version that satisfies the requirement tensorboard<2.2.0,>=2.1.0 (from tensorflow>=2->alibi-detect) (from versions: 1.6.0rc0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0, 1.12.1, 1.12.2, 1.13.0, 1.13.1, 1.14.0, 1.15.0, 2.0.0, 2.0.1, 2.0.2)
ERROR: No matching distribution found for tensorboard<2.2.0,>=2.1.0 (from tensorflow>=2->alibi-detect)
```
my environment is 
`Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)] on win32`

**Comment by jklaise** [comment]
I could not reproduce on either Python 3.6.2 or 3.6.7, I think it might be a tensorflow issue (https://github.com/tensorflow/tensorflow/issues/36380). Can you try uninstalling tensorflow and trying again?
