### ISSUE TITLE
AEGMM Cholesky decomposition error

### ISSUE THREAD

**Issue by mishinma** [SeldonIO/alibi-detect#98]
Hi, 

When training AEGMM on the KDDCUP99 data I often get:
`
InvalidArgumentError: Cholesky decomposition was not successful. The input might not be valid. [Op:Cholesky]
` (raised when computing gmm_params in the loss function). 

Do you know what might cause this? From my experiments seems to be related to the size of `latent_dim`. 

Cheers :)

**Comment by arnaudvl** [comment]
What batch size are you working with? Higher should be more stable.

**Comment by mishinma** [comment]
@arnaudvl I was trying 64 and 1024. The latter indeed seems to be more stable.

**Comment by arnaudvl** [comment]
Closing this now. @mishinma I am also putting some fixes in place for previous issues raised (e.g. #80 and #90 ). Should be merged soon (aiming for tomorrow).
